window.VaultClassifierStrings = Object.freeze({
  "app.title": "Vault Classifier",
  "app.loading": "Loading the local Vault Classifier shell…",
  "hero.offline": "OFFLINE ON THIS MAC",
  "hero.researchEnabled": "LOCAL + OPT-IN RESEARCH",
  "utility.close": "Close",
  "utility.settings.button": "Settings",
  "utility.settings.title": "Local settings",
  "utility.settings.copy": "Configure the on-device model, optional grounded research, and local resource limits.",
  "localModel.title": "Local model",
  "localModel.copy": "Video classification stays on this Mac. If you separately enable Research below, only a sanitized subject is sent to the providers you choose—never the raw title, summary, or body text.",
  "localModel.engineEnabled": "Use the local model engine (off = deterministic debug stub)",
  "localModel.model": "Model file",
  "localModel.modelAuto": "Automatic (first available)",
  "localModel.modelMissing": "{file} (missing — re-download)",
  "localModel.modelHint": "*.gguf files in the app's models folder",
  "localModel.advanced": "Advanced settings",
  "localModel.contextTokens": "Context window",
  "localModel.contextTokensHint": "tokens; bounds prompt + taxonomy + output",
  "localModel.batchTokens": "Prefill batch size",
  "localModel.batchTokensHint": "tokens per prefill pass",
  "localModel.maxOutputTokens": "Max output tokens",
  "localModel.maxOutputTokensHint": "per decision; the contract needs ~2",
  "localModel.maxTags": "Max tags per video",
  "localModel.maxTagsHint": "1–16",
  "localModel.minTags": "Min tags per video",
  "localModel.minTagsHint": "0 = may decline",
  "localModel.temperature": "Temperature",
  "localModel.temperatureHint": "0 = deterministic (recommended)",
  "localModel.maxResidentModels": "Resident model limit",
  "localModel.maxResidentModelsHint": "1–4 distinct GGUF engines kept ready for per-type switching",
  "localModel.gpuOffload": "Run on the GPU (recommended; off = CPU only)",
  "localModel.allowDecline": "Allow the model to decline (\"none\") when no tag fits",
  "localModel.confidence": "Confidence thresholds",
  "localModel.confidenceHint": "probability needed for each confidence level",
  "localModel.houseRules": "House rules",
  "localModel.houseRulesHint": "your tagging preferences, added to every prompt",
  "localModel.save": "Save & reload engine",
  "localModel.status.loaded": "LOADED",
  "localModel.status.loading": "LOADING",
  "localModel.status.disabled": "DISABLED",
  "localModel.status.no-model": "NO MODEL FILE",
  "localModel.status.failed": "LOAD FAILED",
  "modelLibrary.title": "Model library",
  "modelLibrary.copy": "Choose from curated GGUF models that the on-device llama.cpp engine can load directly.",
  "modelLibrary.sourceNote": "Models download from Hugging Face only when you press Download.",
  "modelLibrary.group.small": "Small models",
  "modelLibrary.group.medium": "Medium models",
  "modelLibrary.group.large": "Large models",
  "modelLibrary.params": "{params}B parameters",
  "modelLibrary.size": "{size} GB download",
  "modelLibrary.minimumRAM": "{ram} GB minimum RAM",
  "modelLibrary.recommended": "RECOMMENDED FOR THIS MAC",
  "modelLibrary.latency.green": "GREEN · under 500 ms",
  "modelLibrary.latency.danger": "DANGER · 500 ms–1 s",
  "modelLibrary.latency.reject": "REJECT · over 1 s",
  "modelLibrary.latency.unmeasured": "LATENCY NOT MEASURED",
  "modelLibrary.download": "Download",
  "modelLibrary.cancel": "Cancel",
  "modelLibrary.downloading": "Downloading {progress}",
  "modelLibrary.downloaded": "Downloaded",
  "modelLibrary.delete": "Delete",
  "research.title": "Grounded research",
  "research.status.on": "OPTED IN",
  "research.status.off": "OFF",
  "research.copy": "Optional background grounding for videos the model is unsure about. The global consent below is always the master gate.",
  "research.consent": "I consent to sending sanitized subjects to my selected web-search and language-model providers",
  "research.disclosure": "Data flow: a second on-device constrained decode copies up to three short entities or noun phrases the model did not recognize. Only those sanitized subjects (for example, a quoted show or game name) leave the device, and — once a creator has repeatedly been hard to classify — that creator's public handle. Each is sent to the single grounding-capable provider you select (OpenAI, Gemini, or Anthropic), which performs the web search itself. Raw video titles, summaries, body text, and private creator IDs are never sent.",
  "research.chooseProvider": "Choose a provider",
  "research.llmProvider": "Language-model provider",
  "research.llmProviderHint": "must search the web natively (OpenAI, Gemini, or Anthropic)",
  "research.model": "Language model",
  "research.modelHint": "provider model identifier",
  "research.requestsPerMinute": "Requests per minute",
  "research.requestsPerMinuteHint": "serialized background limit",
  "research.dailyTokenLimit": "Daily token limit",
  "research.dailyTokenLimitHint": "persisted daily usage gate",
  "research.usageToday": "Tokens charged today: {used}",
  "research.status.heading": "Research lane",
  "research.status.queue": "{pending} queued · {inCooldown} in cooldown ({transient} transient) · this session: {succeeded} resolved, {failed} failed, {retries} silent retries, {skippedBudget} deferred by budget",
  "research.status.inFlight": "Researching now: {subject}",
  "research.status.lastFailure": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); next attempt allowed in {retry}",
  "research.status.lastFailure.due": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); retry allowed now",
  "research.status.noFailures": "No research failures recorded.",
  "research.status.retryNow": "Retry failed subjects now",
  "research.status.retryNowHint": "clears every cooldown and re-queues this session's failed subjects",
  "research.failure.timeout": "timed out",
  "research.failure.network": "network error",
  "research.failure.rateLimited": "rate limited",
  "research.failure.serverError": "provider server error",
  "research.failure.providerRejected": "provider rejected the request",
  "research.failure.invalidConfiguration": "invalid research configuration",
  "research.failure.emptyResponse": "empty provider response",
  "research.failure.unknown": "unknown error",
  "research.cooldownHours": "Failure cooldown",
  "research.cooldownHoursHint": "hours before this type retries a failed subject; 1–720",
  "research.urgencyFloor": "Research when",
  "research.urgencyFloorHint": "urgency comes from the model's own tag confidence — the less sure it is about a video, the more urgent",
  "research.urgencyFloor.5": "Only videos it could not tag (declines)",
  "research.urgencyFloor.4": "Declines + very low confidence (≤2)",
  "research.urgencyFloor.3": "Declines + low confidence (≤3)",
  "research.urgencyFloor.2": "Almost everything (confidence ≤4)",
  "research.urgencyFloor.1": "Every video",
  "research.authorCount": "Videos before researching a creator",
  "research.authorCountHint": "how many of a creator's videos must be seen in the window; 1–512",
  "research.authorLevel": "Creator uncertainty level",
  "research.authorLevelHint": "research the creator when those videos average at least this urgency; 1–5",
  "research.authorWindowDays": "Creator window",
  "research.authorWindowDaysHint": "days of history counted; 1–3,650",
  "research.knowledgeTTLDays": "Knowledge lifetime",
  "research.knowledgeTTLDaysHint": "days; 0 keeps grounded knowledge indefinitely",
  "research.maxKnowledgePerVideo": "Knowledge per video",
  "research.maxKnowledgePerVideoHint": "maximum matched entries injected into one prompt; 1–32",
  "research.group.providers": "Providers",
  "research.group.frequency": "Frequency / Budget",
  "research.group.trigger": "Trigger",
  "research.group.author": "Creator research",
  "research.group.knowledge": "Knowledge",
  "research.save": "Save research settings",
  "language.label": "Language",
  "language.name.en": "English",
  "language.name.ar": "العربية",
  "language.name.bn": "বাংলা",
  "language.name.de": "Deutsch",
  "language.name.es": "Español",
  "language.name.fr": "Français",
  "language.name.hi": "हिन्दी",
  "language.name.id": "Bahasa Indonesia",
  "language.name.it": "Italiano",
  "language.name.ja": "日本語",
  "language.name.ko": "한국어",
  "language.name.nl": "Nederlands",
  "language.name.pa": "ਪੰਜਾਬੀ",
  "language.name.pl": "Polski",
  "language.name.pt": "Português",
  "language.name.ru": "Русский",
  "language.name.th": "ไทย",
  "language.name.tr": "Türkçe",
  "language.name.vi": "Tiếng Việt",
  "language.name.zh": "中文",
  "navigation.aria": "Classifier workspaces",
  "navigation.resize": "Resize classifier navigation",
  "navigation.title": "Classifier work",
  "navigation.subtitle": "On-device tagging",
  "navigation.work": "Work",
  "navigation.control": "Control",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "navigation.classifierTypes": "Classifier types",
  "navigation.apiKeys": "API keys",
  "navigation.apiKeysMeta": "Credential profiles & providers",
  "navigation.newType": "New type",
  "navigation.noTypes": "No classifier types yet. Create one for a platform.",
  "navigation.moveUp": "Move up",
  "navigation.moveDown": "Move down",
  "navigation.dragReorder": "Drag to reorder",
  "createType.title": "New classifier group",
  "createType.copy": "Pick a preset — it sets the model behavior and research budget for you. You can fine-tune later under Advanced.",
  "createType.presetLabel": "Preset",
  "createType.platformLabel": "Platform",
  "createType.nameLabel": "Group name",
  "createType.create": "Create group",
  "createType.defaultName": "New group",
  "preset.gentle.name": "Gentle",
  "preset.gentle.desc": "Blocks only on very high confidence. Declines freely, light research.",
  "preset.balanced.name": "Balanced",
  "preset.balanced.desc": "The everyday default. Blocks on solid confidence; researches declines and low-confidence guesses.",
  "preset.strict.name": "Strict",
  "preset.strict.desc": "Blocks on modest confidence. Commits to a tag rather than declining, with more research budget.",
  "preset.localOnly.name": "Local only",
  "preset.localOnly.desc": "Same blocking as Balanced, fully on-device — no network research.",
  "preset.default.badge": "Recommended",
  "preset.modifiedFrom": "Modified from {name}",
  "preset.basedOn": "Based on {name}",
  "bridge.tabConfig": "Config",
  "bridge.tabTree": "Tag tree",
  "settings.apiKeysTitle": "API keys & providers",
  "settings.apiKeysCopy": "Credential profiles for LLM assist and platform data.",
  "settings.manageApiKeys": "Manage API keys",
  "settings.packageUpdates": "Package updates",
  "settings.packageUpdatesCopy": "Choose how verified taxonomy package updates are activated.",
  "common.save": "Save",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.update.automatic": "Automatic",
  "enum.update.downloadThenAsk": "Ask first",
  "enum.update.manual": "Manual",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "common.delete": "Delete",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this Mac's settings, taxonomy, and collected workspace configuration. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in this Mac's Keychain. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "Owner code",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current local snapshot plus three previous snapshots.",
  "backup.localFolder": "Local folder",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after local configuration changes",
  "backup.save": "Save backup mode",
  "backup.create": "Create backup now",
  "integration.title": "Browser bridge",
  "integration.copy": "The Chrome and Edge adapter requires registered Native Messaging authentication.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Local authentication",
  "integration.keychain": "Keychain-backed proof",
  "integration.host": "Native host",
  "integration.notRegistered": "Requires installer registration",
  "integration.server": "Protocol",
  "integration.notRequired": "Version 4",
  "integration.notice": "A signed installer must supply confirmed stable extension IDs and the host path. Until then, Chrome and Edge stay disconnected rather than using an unauthenticated bridge.",
  "navigation.tagTree": "Tag tree",
  "navigation.tagTreeMeta": "Shared tree library",
  "navigation.llmAssist": "LLM assist",
  "navigation.llmAssistMeta": "Credential profiles",
  "navigation.browserBridge": "Classifier Type",
  "navigation.browserBridgeMeta": "Decision brains",
  "navigation.classificationData": "Classification data",
  "navigation.classificationDataMeta": "Collection and video tags",
  "navigation.knowledge": "Knowledge",
  "navigation.knowledgeMeta": "Known creators & terms",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.title": "Tag tree",
  "tree.copy": "Create and evolve reusable local tag trees. Every edit publishes a new revision.",
  "tree.sharedLibrary": "Shared library",
  "tree.active": "Active tree",
  "tree.activeCopy": "Current local revision {revision}",
  "tree.inspector": "Node inspector",
  "tree.inspectorCopy": "Changes publish a new tree revision for subsequent classifications.",
  "tree.activeNode": "ACTIVE",
  "tree.nodeName": "Node name",
  "tree.level": "Level {value}",
  "tree.rootNode": "Root node",
  "tree.childOf": "Child of {name}",
  "tree.nodeCount": "{count} nodes",
  "tree.panel": "Tree panel",
  "tree.multiplePanels": "Each tree keeps its own editing panel.",
  "tree.contextHint": "Click or right-click to edit this node",
  "tree.saveNode": "Save node",
  "tree.createNode": "Create node",
  "tree.editNode": "Edit node",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a node to make it the parent.",
  "tree.connection": "Connection",
  "tree.disconnection": "Disconnection",
  "tree.deleteNode": "Delete node",
  "tree.rename": "Rename",
  "tree.renameTree": "Rename tree",
  "tree.saveTreeName": "Save tree",
  "tree.rearrange": "Rearrange",
  "tree.delete": "Delete",
  "tree.confirmDelete": "Delete tree?",
  "tree.confirmDeleteCopy": "This permanently removes the tree and any platform link to it.",
  "tree.confirmDeleteAction": "Delete tree",
  "tree.canvasHint": "Right-click empty space to create a root node. Click or right-click a node to edit it. Drag a node to reposition its branch.",
  "tree.empty": "No nodes are in this local tree yet.",
  "tree.addTag": "Add a tag",
  "tree.addCopy": "Tags stay local. Adding a node creates a new tree revision.",
  "tree.tagName": "Tag name",
  "tree.tagDescription": "Tag description",
  "tree.tagDescriptionCopy": "Optional local context sent with this eligible tag in LLM classification requests.",
  "tree.add": "Add local tag",
  "tree.newTree": "New tag tree",
  "tree.newCopy": "A new tree is a reusable library asset. Bind it deliberately to a browser platform.",
  "tree.treeName": "Tree name",
  "tree.create": "Create tree",
  "llm.title": "LLM assist",
  "llm.copy": "Create local language-model, blockable-platform data, or raw web-search profiles.",
  "llm.localOnlyDisclosure": "Your API keys are stored locally on this Mac, inside this app's own support folder — never in the system keychain. They are used only to call the provider you entered them for. We never upload your keys anywhere.",
  "llm.keyLibrary": "Key library",
  "llm.providerType": "Provider type",
  "llm.chooseProviderType": "Choose a provider type",
  "llm.createKey": "Create key",
  "llm.createCopy": "Use a direct model preset, an official platform-data API, Serper or You.com Search, or a compatible custom model endpoint.",
  "llm.empty": "No API-key profiles yet. Choose a provider type, then create its local setup panel.",
  "llm.providerPanel": "Provider panel",
  "llm.provider.openAI": "OpenAI",
  "llm.provider.openAICompatible": "OpenAI-compatible API",
  "llm.provider.deepSeek": "DeepSeek",
  "llm.provider.gemini": "Gemini",
  "llm.provider.anthropic": "Anthropic",
  "llm.provider.mistral": "Mistral AI",
  "llm.provider.cohere": "Cohere",
  "llm.provider.groq": "Groq",
  "llm.provider.openRouter": "OpenRouter",
  "llm.provider.ollama": "Ollama",
  "llm.provider.youtubeData": "YouTube Data API",
  "llm.provider.twitch": "Twitch",
  "llm.provider.reddit": "Reddit",
  "llm.provider.xPlatform": "X API",
  "llm.provider.tikTok": "TikTok",
  "llm.provider.instagramGraph": "Instagram Graph API",
  "llm.provider.facebookGraph": "Facebook Graph API",
  "llm.retiredSearchProvider": "Web-search APIs are no longer used: research now searches through your grounding-capable model provider. This saved profile is kept but inactive — you can delete it.",
  "llm.provider.serper": "Serper",
  "llm.provider.youSearch": "You.com Search",
  "llm.provider.custom": "Custom API",
  "llm.providerGroup.models": "Language models",
  "llm.providerGroup.platform": "BLOCKABLE PLATFORM DATA APIs",
  "llm.providerGroup.custom": "CUSTOM AND COMPATIBLE APIs",
  "llm.deleteProfile": "Delete profile",
  "llm.apiKeyOrToken": "API key or token",
  "llm.apiEndpoint": "API endpoint",
  "llm.testModel": "Model for test",
  "llm.test": "Test request",
  "llm.testing": "Testing…",
  "llm.testSucceeded": "Test request succeeded. The provider is ready.",
  "llm.tokenUsage": "Token usage",
  "llm.tokenTotal": "{total} aggregate tokens",
  "llm.apiCalls": "API calls",
  "llm.responseShape": "Last unparseable response shape",
  "llm.protocol.accountID": "Account ID",
  "llm.protocol.apiVersion": "API version",
  "llm.protocol.clientID": "Client ID",
  "llm.protocol.location": "Location",
  "llm.protocol.projectID": "Project ID",
  "llm.protocol.region": "Region",
  "llm.protocol.userAgent": "User agent",
  "llm.protocol.searchEngineID": "Search engine ID",
  "llm.protocol.protocolFamily": "Request family",
  "bridge.title": "Classifier Type",
  "bridge.copy": "Build local decision brains from platform data, tag trees, and optional on-device model overrides. Browser connection controls live in Settings.",
  "bridge.typeLibrary": "Decision brain library",
  "bridge.typePanel": "Classifier type",
  "bridge.newTypeName": "New classifier type",
  "bridge.newTypeNameCopy": "For example, YouTube creator focus",
  "bridge.createType": "Create type",
  "bridge.emptyTypes": "Create a classifier type to assemble a local decision brain.",
  "bridge.selectType": "Select a classifier type on the left, or click + New type.",
  "bridge.typeName": "Type name",
  "bridge.saveType": "Save type",
  "bridge.deleteType": "Delete type",
  "bridge.typeMatchCopy": "Tag tree: {tree} · Local data: {data}",
  "bridge.missingAsset": "Missing asset",
  "bridge.configured": "CONFIGURED",
  "bridge.needsSource": "NEEDS SOURCE",
  "bridge.assetSelectionCopy": "Choose one platform. Its platform binding supplies this type's tag tree and collected classification data.",
  "bridge.applicablePlatform": "Applicable platform",
  "bridge.platformData": "Platform data",
  "bridge.applicablePlatformCopy": "Only one platform can be used by a classifier type.",
  "common.cancel": "Cancel",
  "trash.confirmTitle": "Delete this — are you sure?",
  "trash.confirmCopy": "This moves “{name}” and all of its data to the trash. It is recoverable for 24 hours, then permanently purged.",
  "trash.typeNameLabel": "Type the name to confirm",
  "trash.confirmDelete": "Delete",
  "trash.deleted": "DELETED · restorable for 24h",
  "trash.title": "Trash",
  "trash.restore": "Restore entry",
  "trash.permanentlyDelete": "Permanently delete",
  "bridge.noApplicablePlatform": "Choose a platform",
  "bridge.platformDataChoose": "Choose a platform to bind its local classification data.",
  "bridge.platformDataAutoCreate": "adds local data",
  "bridge.platformDataWillCreate": "Local classification data for {platform} will be added when you save this type.",
  "bridge.platformDataBound": "Official API evidence connection: {profile}",
  "bridge.platformDataMissingKey": "No local {platform} official API credential is configured.",
  "bridge.platformDataUnavailable": "{platform} has no official API evidence adapter.",
  "bridge.collectionOnly": "Collection only",
  "bridge.collectionOnlyCopy": "This platform can collect public entries, but per-type on-device model overrides are unavailable.",
  "bridge.localModelOverrides": "Local model overrides",
  "bridge.localModelOverridesCopy": "Choose a model for this classifier type, and optionally replace its app-wide house rules, decline behavior, and confidence bands. Runtime controls remain global.",
  "bridge.localModelFile": "Model file",
  "bridge.localModelFileCopy": "a GGUF for this type, or inherit the global model",
  "bridge.localModelInheritGlobal": "Inherit global model",
  "bridge.localModelResidentNote": "Up to {count} models resident ≈ {count}× model RAM. Least-recently-used models unload automatically.",
  "bridge.localModelOverrideEnabled": "Use overrides for this classifier type",
  "bridge.localModelOverrideControls": "Override controls",
  "bridge.localModelAllowDecline": "Allow this type to decline (\"none\") when no tag fits",
  "bridge.localModelOcrEvidence": "Read thumbnail text (OCR) as extra classification evidence",
  "bridge.localModelMaxTags": "Max tags per video for this type",
  "bridge.localModelMinTags": "Min tags per video for this type",
  "bridge.localModelHouseRules": "Type house rules",
  "bridge.localModelHouseRulesCopy": "tagging preferences for this classifier type; replaces the app-wide house rules",
  "bridge.researchOverrides": "Grounded research",
  "bridge.researchOverridesCopy": "Optionally replace the app-wide research defaults for this classifier type.",
  "bridge.researchOverrideEnabled": "Use research overrides for this classifier type",
  "bridge.researchOverrideControls": "Research override controls",
  "bridge.researchEnabled": "Enable grounded research for this classifier type",
  "bridge.researchMasterGate": "The global Research consent in Settings is the master gate. This type can never research while global consent is off.",
  "bridge.sourceKind.creator": "creator",
  "bridge.sourceKind.creatorPlural": "creators",
  "bridge.sourceKind.account": "account",
  "bridge.sourceKind.accountPlural": "accounts",
  "bridge.sourceKind.subreddit": "subreddit",
  "bridge.sourceKind.subredditPlural": "subreddits",
  "bridge.sourceKind.server": "Discord server",
  "bridge.sourceKind.serverPlural": "Discord servers",
  "bridge.sourceCount": "{count} {sources}",
  "bridge.notTag": "Not",
  "bridge.searchSources": "Search by name…",
  "bridge.searchCount": "{shown} of {total}",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, and compatible model.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "Asset binding",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.configure": "Configure locally",
  "data.title": "Classification data",
  "data.copy": "Add each public-content platform once, choose whether its rendered metadata is collected locally, and review entries by source.",
  "data.entries": "{count} COLLECTED ENTRIES",
  "data.addPlatform": "Add platform",
  "data.addPlatformCopy": "A platform owns one local tree and dataset binding. Collection starts on and sends only rendered public entries when this browser is connected.",
  "data.addPlatformAction": "Add platform",
  "data.allPlatformsAdded": "Every currently known public-content platform has been added.",
  "data.noPlatforms": "Add a platform to begin a local collection library.",
  "data.platform": "Platform",
  "data.platformPanel": "Platform collection",
  "data.deletePlatform": "Delete platform",
  "data.collectorAvailable": "Collector available",
  "data.collectorPlanned": "Collector not installed yet",
  "data.collecting": "COLLECTING",
  "data.collectionOff": "COLLECTION OFF",
  "data.collectToggle": "Collect rendered public entries on this platform",
  "data.applyCollection": "Apply collection setting",
  "data.classifierType": "Classifier type",
  "data.classifierTypeCopy": "Selects the local decision configuration used for this platform",
  "data.noClassifierType": "No classifier type (legacy local engine)",
  "data.applyClassifierType": "Apply classifier type",
  "data.classifierTypeActive": "TYPE ACTIVE",
  "data.classifierTypeNone": "LEGACY ENGINE",
  "data.collectionDisabledCopy": "Collection is off. No entry title or source metadata is sent from the extension.",
  "data.waitingForEntries": "Collection is on. New rendered, non-ad entries will appear here by source.",
  "data.sourceCount": "{count} {sources}",
  "data.entryCount": "{count} entries",
  "knowledge.title": "Knowledge",
  "knowledge.copy": "Grounded descriptions the classifier has learned. Creators steer their videos' low-confidence tags; terms add context when they appear in a title.",
  "knowledge.badge": "On-device",
  "knowledge.disclosure": "These descriptions are stored locally on this Mac. Editing a creator's description changes how that creator's low-confidence videos are tagged. Deleting an entry forgets it — a creator can then be re-researched.",
  "knowledge.creators": "Known creators",
  "knowledge.creatorsHint": "Kept permanently and used to infer tags for a creator's low-confidence videos.",
  "knowledge.terms": "Known terms",
  "knowledge.termsHint": "Entities and titles; injected only when they appear in a video's title.",
  "knowledge.description": "Description",
  "knowledge.permanent": "Permanent",
  "knowledge.delete": "Forget",
  "knowledge.empty": "Nothing learned yet. Grounded research adds entries here as it runs.",
  "data.correctClassification": "Correct classification",
  "data.correctionCopy": "Your correction is saved locally, becomes the authoritative pill result, and is distilled into this classifier type's learned house rules in batches of five. It triggers sanitized subject research only when the type's Research trigger includes corrections.",
  "data.correctTags": "Correct tags",
  "data.correctTagsHint": "select none to record an explicit decline",
  "data.correctionNote": "Optional note",
  "data.correctionNoteHint": "local preference context",
  "data.saveCorrection": "Save correction",
  "data.corrected": "CORRECTED",
  "data.discordLocalOnly": "Discord collects rendered messages from server channels you open in the browser, never direct messages. The collected content stays on this Mac and is never sent to a provider or remote service.",
  "data.unknownDate": "Unknown observation time",
  "data.diagnostics": "Collection diagnostics",
  "data.diagnosticsCopy": "Local pipeline checkpoints only. They never include page text, titles, creators, URLs, or entry IDs.",
  "data.clearDiagnostics": "Clear diagnostics",
  "data.noDiagnostics": "No collection checkpoints yet. Open a supported page to record the next attempt."
});
