window.VaultClassifierStrings = Object.freeze({
  "app.title": "Vault Classifier",
  "app.loading": "Loading the local Vault Classifier shell…",
  "hero.offline": "OFFLINE ON THIS MAC",
  "hero.researchEnabled": "LOCAL + OPT-IN RESEARCH",
  "utility.close": "Close",
  "utility.settings.button": "Settings",
  "utility.settings.title": "Local settings",
  "utility.settings.copy": "Configure the on-device model, optional grounded research, and local resource limits.",
  "localModel.title": "Local model",
  "localModel.copy": "Video classification stays on this Mac. Two dials set everything: which model runs, and how many tags a video may carry. If you separately enable Research below, only a sanitized subject is sent to the provider you choose—never the raw title, summary, or thumbnail.",
  "localModel.speedQuality": "Speed ↔ Quality",
  "localModel.speedQualityHint": "which model tier runs; a tier must be downloaded before it can classify",
  "localModel.tier.fast.name": "Fast",
  "localModel.tier.fast.desc": "About half the time per video; noticeably fewer correct tags.",
  "localModel.tier.balanced.name": "Balanced",
  "localModel.tier.balanced.desc": "The measured default: the best trade-off on a 16 GB Mac.",
  "localModel.tier.best.name": "Best",
  "localModel.tier.best.desc": "A few more correct tags at about twice the time per video.",
  "localModel.tier.model": "{model} · {size} GB · needs {ram} GB RAM",
  "localModel.tier.ramShort": "This Mac has less than {ram} GB RAM — it may be slow or fail to load.",
  "localModel.tier.recommended": "RECOMMENDED FOR THIS MAC",
  "localModel.tier.sourceNote": "Models download from Hugging Face only when you press Download.",
  "localModel.strictness": "Strict ↔ Broad",
  "localModel.strictnessHint": "how many tags a video may carry, and how sure the model must be before it keeps an extra one",
  "localModel.strictness.1.name": "Strictest",
  "localModel.strictness.1.desc": "One tag per video, and only when the model is sure. Fewest wrong tags; about one video in six stays untagged.",
  "localModel.strictness.2.name": "Strict",
  "localModel.strictness.2.desc": "Up to three tags; an extra tag is kept only when the model is very sure of it.",
  "localModel.strictness.3.name": "Balanced",
  "localModel.strictness.3.desc": "Up to three tags; the measured default.",
  "localModel.strictness.4.name": "Broad",
  "localModel.strictness.4.desc": "Up to three tags; extra tags are kept a little more readily.",
  "localModel.strictness.5.name": "Broadest",
  "localModel.strictness.5.desc": "Like Broad, and the model must always tag — nothing stays untagged, at the cost of more wrong tags.",
  "localModel.strictness.followGlobal": "Follow the global dial ({name})",
  "localModel.speedQuality.followGlobal": "Follow the global dial ({name})",
  "localModel.tier.notDownloaded": "{name} (not downloaded)",
  "localModel.houseRules": "House rules",
  "localModel.houseRulesHint": "your tagging preferences, added to every prompt",
  "localModel.save": "Save & reload engine",
  "localModel.status.loaded": "LOADED",
  "localModel.status.loading": "LOADING",
  "localModel.status.disabled": "DISABLED",
  "localModel.status.no-model": "MODEL NOT DOWNLOADED",
  "localModel.status.failed": "LOAD FAILED",
  "modelLibrary.download": "Download",
  "modelLibrary.cancel": "Cancel",
  "modelLibrary.downloading": "Downloading {progress}",
  "modelLibrary.downloaded": "Downloaded",
  "modelLibrary.delete": "Delete",
  "research.title": "Grounded research",
  "research.status.on": "OPTED IN",
  "research.status.off": "OFF",
  "research.copy": "Optional background lookups: creators whose videos stay hard to classify, and terms you add yourself. On or off, plus the provider that answers. The global consent below is always the master gate.",
  "research.consent": "I consent to sending sanitized subjects to my selected web-search and language-model providers",
  "research.disclosure": "Data flow: only two kinds of text ever leave the device — the public handle of a creator who has repeatedly been hard to classify, and a term you chose to add in Knowledge without writing its description. Each is sent to the single grounding-capable provider you select (OpenAI, Gemini, or Anthropic), which performs the web search itself. Video titles, summaries, body text, and private creator IDs are never sent.",
  "research.chooseProvider": "Choose a provider",
  "research.llmProvider": "Language-model provider",
  "research.llmProviderHint": "must search the web natively (OpenAI, Gemini, or Anthropic)",
  "research.model": "Language model",
  "research.modelHint": "provider model identifier",
  "research.usageToday": "Tokens charged today: {used} of {limit}",
  "research.constantsNote": "Fixed: at most 6 lookups a minute and 10,000 tokens a day; a creator is looked up once its videos have stayed hard to tag (score 3, fading by half every 14 days); grounded knowledge never expires.",
  "research.status.heading": "Research lane",
  "research.status.queue": "{pending} queued · {inCooldown} in cooldown ({transient} transient) · this session: {succeeded} resolved, {failed} failed, {retries} silent retries, {skippedBudget} deferred by budget",
  "research.status.inFlight": "Researching now: {subject}",
  "research.status.lastFailure": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); next attempt allowed in {retry}",
  "research.status.lastFailure.due": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); retry allowed now",
  "research.status.noFailures": "No research failures recorded.",
  "research.status.retryNow": "Retry failed subjects now",
  "research.status.retryNowHint": "clears every cooldown and re-queues this session's failed subjects",
  "research.failure.timeout": "timed out",
  "research.failure.network": "network error",
  "research.failure.rateLimited": "rate limited",
  "research.failure.serverError": "provider server error",
  "research.failure.providerRejected": "provider rejected the request",
  "research.failure.invalidConfiguration": "invalid research configuration",
  "research.failure.emptyResponse": "empty provider response",
  "research.failure.unknown": "unknown error",
  "research.group.providers": "Providers",
  "research.save": "Save research settings",
  "language.label": "Language",
  "language.name.en": "English",
  "language.name.ar": "العربية",
  "language.name.bn": "বাংলা",
  "language.name.de": "Deutsch",
  "language.name.es": "Español",
  "language.name.fr": "Français",
  "language.name.hi": "हिन्दी",
  "language.name.id": "Bahasa Indonesia",
  "language.name.it": "Italiano",
  "language.name.ja": "日本語",
  "language.name.ko": "한국어",
  "language.name.nl": "Nederlands",
  "language.name.pa": "ਪੰਜਾਬੀ",
  "language.name.pl": "Polski",
  "language.name.pt": "Português",
  "language.name.ru": "Русский",
  "language.name.th": "ไทย",
  "language.name.tr": "Türkçe",
  "language.name.vi": "Tiếng Việt",
  "language.name.zh": "中文",
  "navigation.aria": "Classifier workspaces",
  "navigation.resize": "Resize classifier navigation",
  "navigation.title": "Classifier work",
  "navigation.subtitle": "On-device tagging",
  "navigation.work": "Work",
  "navigation.control": "Control",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "navigation.classifierTypes": "Classifier types",
  "navigation.apiKeys": "API keys",
  "navigation.apiKeysMeta": "Credential profiles & providers",
  "navigation.newType": "New type",
  "navigation.noTypes": "No classifier types yet. Create one for a platform.",
  "navigation.moveUp": "Move up",
  "navigation.moveDown": "Move down",
  "navigation.dragReorder": "Drag to reorder",
  "createType.title": "New classifier group",
  "createType.copy": "A group tags one platform with its own tag tree. It follows the global dials until you give it its own.",
  "createType.platformLabel": "Platform",
  "createType.nameLabel": "Group name",
  "createType.create": "Create group",
  "createType.defaultName": "New group",
  "bridge.tabConfig": "Config",
  "bridge.tabTree": "Tag tree",
  "settings.apiKeysTitle": "API keys & providers",
  "settings.apiKeysCopy": "Credential profiles for LLM assist and platform data.",
  "settings.manageApiKeys": "Manage API keys",
  "settings.packageUpdates": "Package updates",
  "settings.packageUpdatesCopy": "Choose how verified taxonomy package updates are activated.",
  "common.save": "Save",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.update.automatic": "Automatic",
  "enum.update.downloadThenAsk": "Ask first",
  "enum.update.manual": "Manual",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "common.delete": "Delete",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this Mac's settings, taxonomy, and collected workspace configuration. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in this Mac's Keychain. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "Owner code",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current local snapshot plus three previous snapshots.",
  "backup.localFolder": "Local folder",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after local configuration changes",
  "backup.save": "Save backup mode",
  "backup.create": "Create backup now",
  "integration.title": "Browser bridge",
  "integration.copy": "The Chrome and Edge adapter requires registered Native Messaging authentication.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Local authentication",
  "integration.keychain": "Keychain-backed proof",
  "integration.host": "Native host",
  "integration.notRegistered": "Requires installer registration",
  "integration.server": "Protocol",
  "integration.notRequired": "Version 4",
  "integration.notice": "A signed installer must supply confirmed stable extension IDs and the host path. Until then, Chrome and Edge stay disconnected rather than using an unauthenticated bridge.",
  "navigation.tagTree": "Tag tree",
  "navigation.tagTreeMeta": "Shared tree library",
  "navigation.llmAssist": "LLM assist",
  "navigation.llmAssistMeta": "Credential profiles",
  "navigation.browserBridge": "Classifier Type",
  "navigation.browserBridgeMeta": "Decision brains",
  "navigation.classificationData": "History",
  "navigation.classificationDataMeta": "Collected videos and their tags",
  "navigation.knowledge": "Knowledge",
  "navigation.knowledgeMeta": "Known creators & terms",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.title": "Tag tree",
  "tree.copy": "Create and evolve reusable local tag trees. Every edit publishes a new revision.",
  "tree.sharedLibrary": "Shared library",
  "tree.active": "Active tree",
  "tree.activeCopy": "Current local revision {revision}",
  "tree.inspector": "Node inspector",
  "tree.inspectorCopy": "Changes publish a new tree revision for subsequent classifications.",
  "tree.activeNode": "ACTIVE",
  "tree.nodeName": "Node name",
  "tree.level": "Level {value}",
  "tree.rootNode": "Root node",
  "tree.childOf": "Child of {name}",
  "tree.nodeCount": "{count} nodes",
  "tree.panel": "Tree panel",
  "tree.multiplePanels": "Each tree keeps its own editing panel.",
  "tree.contextHint": "Click or right-click to edit this node",
  "tree.saveNode": "Save node",
  "tree.createNode": "Create node",
  "tree.editNode": "Edit node",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a node to make it the parent.",
  "tree.connection": "Connection",
  "tree.disconnection": "Disconnection",
  "tree.deleteNode": "Delete node",
  "tree.rename": "Rename",
  "tree.renameTree": "Rename tree",
  "tree.saveTreeName": "Save tree",
  "tree.rearrange": "Rearrange",
  "tree.delete": "Delete",
  "tree.confirmDelete": "Delete tree?",
  "tree.confirmDeleteCopy": "This permanently removes the tree and any platform link to it.",
  "tree.confirmDeleteAction": "Delete tree",
  "tree.canvasHint": "Right-click empty space to create a root node. Click or right-click a node to edit it. Drag a node to reposition its branch.",
  "tree.empty": "No nodes are in this local tree yet.",
  "tree.addTag": "Add a tag",
  "tree.addCopy": "Tags stay local. Adding a node creates a new tree revision.",
  "tree.tagName": "Tag name",
  "tree.tagDescription": "Tag description",
  "tree.tagDescriptionCopy": "Optional local context sent with this eligible tag in LLM classification requests.",
  "tree.add": "Add local tag",
  "tree.newTree": "New tag tree",
  "tree.newCopy": "A new tree is a reusable library asset. Bind it deliberately to a browser platform.",
  "tree.treeName": "Tree name",
  "tree.create": "Create tree",
  "llm.title": "LLM assist",
  "llm.copy": "Create local language-model, blockable-platform data, or raw web-search profiles.",
  "llm.localOnlyDisclosure": "Your API keys are stored locally on this Mac, inside this app's own support folder — never in the system keychain. They are used only to call the provider you entered them for. We never upload your keys anywhere.",
  "llm.keyLibrary": "Key library",
  "llm.providerType": "Provider type",
  "llm.chooseProviderType": "Choose a provider type",
  "llm.createKey": "Create key",
  "llm.createCopy": "Use a direct model preset, an official platform-data API, Serper or You.com Search, or a compatible custom model endpoint.",
  "llm.empty": "No API-key profiles yet. Choose a provider type, then create its local setup panel.",
  "llm.providerPanel": "Provider panel",
  "llm.provider.openAI": "OpenAI",
  "llm.provider.openAICompatible": "OpenAI-compatible API",
  "llm.provider.deepSeek": "DeepSeek",
  "llm.provider.gemini": "Gemini",
  "llm.provider.anthropic": "Anthropic",
  "llm.provider.mistral": "Mistral AI",
  "llm.provider.cohere": "Cohere",
  "llm.provider.groq": "Groq",
  "llm.provider.openRouter": "OpenRouter",
  "llm.provider.ollama": "Ollama",
  "llm.provider.youtubeData": "YouTube Data API",
  "llm.provider.twitch": "Twitch",
  "llm.provider.reddit": "Reddit",
  "llm.provider.xPlatform": "X API",
  "llm.provider.tikTok": "TikTok",
  "llm.provider.instagramGraph": "Instagram Graph API",
  "llm.provider.facebookGraph": "Facebook Graph API",
  "llm.retiredSearchProvider": "Web-search APIs are no longer used: research now searches through your grounding-capable model provider. This saved profile is kept but inactive — you can delete it.",
  "llm.provider.serper": "Serper",
  "llm.provider.youSearch": "You.com Search",
  "llm.provider.custom": "Custom API",
  "llm.providerGroup.models": "Language models",
  "llm.providerGroup.platform": "BLOCKABLE PLATFORM DATA APIs",
  "llm.providerGroup.custom": "CUSTOM AND COMPATIBLE APIs",
  "llm.deleteProfile": "Delete profile",
  "llm.apiKeyOrToken": "API key or token",
  "llm.apiEndpoint": "API endpoint",
  "llm.testModel": "Model for test",
  "llm.test": "Test request",
  "llm.testing": "Testing…",
  "llm.testSucceeded": "Test request succeeded. The provider is ready.",
  "llm.tokenUsage": "Token usage",
  "llm.tokenTotal": "{total} aggregate tokens",
  "llm.apiCalls": "API calls",
  "llm.responseShape": "Last unparseable response shape",
  "llm.protocol.accountID": "Account ID",
  "llm.protocol.apiVersion": "API version",
  "llm.protocol.clientID": "Client ID",
  "llm.protocol.location": "Location",
  "llm.protocol.projectID": "Project ID",
  "llm.protocol.region": "Region",
  "llm.protocol.userAgent": "User agent",
  "llm.protocol.searchEngineID": "Search engine ID",
  "llm.protocol.protocolFamily": "Request family",
  "bridge.title": "Classifier Type",
  "bridge.copy": "Build local decision brains from platform data, tag trees, and optional on-device model overrides. Browser connection controls live in Settings.",
  "bridge.typeLibrary": "Decision brain library",
  "bridge.typePanel": "Classifier type",
  "bridge.newTypeName": "New classifier type",
  "bridge.newTypeNameCopy": "For example, YouTube creator focus",
  "bridge.createType": "Create type",
  "bridge.emptyTypes": "Create a classifier type to assemble a local decision brain.",
  "bridge.selectType": "Select a classifier type on the left, or click + New type.",
  "bridge.typeName": "Type name",
  "bridge.saveType": "Save type",
  "bridge.deleteType": "Delete type",
  "bridge.typeMatchCopy": "Tag tree: {tree} · Local data: {data}",
  "bridge.missingAsset": "Missing asset",
  "bridge.configured": "CONFIGURED",
  "bridge.needsSource": "NEEDS SOURCE",
  "bridge.assetSelectionCopy": "Choose one platform. Its platform binding supplies this type's tag tree and collected classification data.",
  "bridge.applicablePlatform": "Applicable platform",
  "bridge.platformData": "Platform data",
  "bridge.applicablePlatformCopy": "Only one platform can be used by a classifier type.",
  "common.cancel": "Cancel",
  "trash.confirmTitle": "Delete this — are you sure?",
  "trash.confirmCopy": "This moves “{name}” and all of its data to the trash. It is recoverable for 24 hours, then permanently purged.",
  "trash.typeNameLabel": "Type the name to confirm",
  "trash.confirmDelete": "Delete",
  "trash.deleted": "DELETED · restorable for 24h",
  "trash.title": "Trash",
  "trash.restore": "Restore entry",
  "trash.permanentlyDelete": "Permanently delete",
  "bridge.noApplicablePlatform": "Choose a platform",
  "bridge.platformDataChoose": "Choose a platform to bind its local classification data.",
  "bridge.platformDataAutoCreate": "adds local data",
  "bridge.platformDataWillCreate": "Local classification data for {platform} will be added when you save this type.",
  "bridge.platformDataBound": "Official API evidence connection: {profile}",
  "bridge.platformDataMissingKey": "No local {platform} official API credential is configured.",
  "bridge.platformDataUnavailable": "{platform} has no official API evidence adapter.",
  "bridge.collectionOnly": "Collection only",
  "bridge.collectionOnlyCopy": "This platform can collect public entries, but per-type on-device model overrides are unavailable.",
  "bridge.localModelOverrides": "Local model for this group",
  "bridge.localModelOverridesCopy": "This group follows the global dials and house rules unless you set its own here.",
  "bridge.localModelHouseRules": "Group house rules",
  "bridge.localModelHouseRulesCopy": "tagging preferences for this group; replaces the app-wide house rules",
  "bridge.localModelResidentNote": "A group on another tier than the global dial keeps a second model loaded (≈ that model's RAM).",
  "bridge.researchOverrides": "Grounded research",
  "bridge.researchOverridesCopy": "Whether this group may research creators and terms.",
  "bridge.researchMode": "Research for this group",
  "bridge.researchMode.inherit": "Follow the global switch",
  "bridge.researchMode.on": "On",
  "bridge.researchMode.off": "Off",
  "bridge.researchMasterGate": "The global Research consent in Settings is the master gate. This group can never research while global consent is off.",
  "bridge.sourceKind.creator": "creator",
  "bridge.sourceKind.creatorPlural": "creators",
  "bridge.sourceKind.account": "account",
  "bridge.sourceKind.accountPlural": "accounts",
  "bridge.sourceKind.subreddit": "subreddit",
  "bridge.sourceKind.subredditPlural": "subreddits",
  "bridge.sourceKind.server": "Discord server",
  "bridge.sourceKind.serverPlural": "Discord servers",
  "bridge.sourceCount": "{count} {sources}",
  "bridge.notTag": "Not",
  "bridge.searchSources": "Search by name…",
  "bridge.searchCount": "{shown} of {total}",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, and compatible model.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "Asset binding",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.configure": "Configure locally",
  "data.title": "History",
  "data.copy": "Add each public-content platform once, choose whether its rendered metadata is collected locally, and review entries by source.",
  "data.entries": "{count} COLLECTED ENTRIES",
  "data.addPlatform": "Add platform",
  "data.addPlatformCopy": "A platform owns one local tree and dataset binding. Collection starts on and sends only rendered public entries when this browser is connected.",
  "data.addPlatformAction": "Add platform",
  "data.allPlatformsAdded": "Every currently known public-content platform has been added.",
  "data.noPlatforms": "Add a platform to begin a local collection library.",
  "data.platform": "Platform",
  "data.platformPanel": "Platform collection",
  "data.deletePlatform": "Delete platform",
  "data.collectorAvailable": "Collector available",
  "data.collectorPlanned": "Collector not installed yet",
  "data.collecting": "COLLECTING",
  "data.collectionOff": "COLLECTION OFF",
  "data.collectToggle": "Collect rendered public entries on this platform",
  "data.applyCollection": "Apply collection setting",
  "data.classifierType": "Classifier type",
  "data.classifierTypeCopy": "Selects the local decision configuration used for this platform",
  "data.noClassifierType": "No classifier type (legacy local engine)",
  "data.applyClassifierType": "Apply classifier type",
  "data.classifierTypeActive": "TYPE ACTIVE",
  "data.classifierTypeNone": "LEGACY ENGINE",
  "data.collectionDisabledCopy": "Collection is off. No entry title or source metadata is sent from the extension.",
  "data.waitingForEntries": "Collection is on. New rendered, non-ad entries will appear here by source.",
  "data.sourceCount": "{count} {sources}",
  "data.entryCount": "{count} entries",
  "knowledge.title": "Knowledge",
  "knowledge.copy": "What the classifier knows beyond the title: one sentence per creator or term. A creator's sentence is read with every video of theirs; a term's whenever it appears in a title.",
  "knowledge.badge": "On-device",
  "knowledge.disclosure": "These sentences are stored locally on this Mac and read by the on-device model, so keep them short — every word costs tagging time. Editing a creator's sentence changes how all their videos are tagged. Deleting an entry forgets it — a creator can then be re-researched.",
  "knowledge.creators": "Known creators",
  "knowledge.creatorsHint": "Researched automatically once a creator keeps being hard to tag; read with every video of theirs.",
  "knowledge.terms": "Known terms",
  "knowledge.termsHint": "Names you added; used only when they appear in a video's title.",
  "knowledge.addTerm": "Add a term",
  "knowledge.addTermHint": "A name the classifier does not know — a game, show, person, server, in-joke. Leave the description empty to have it looked up.",
  "knowledge.termSubject": "Term",
  "knowledge.termSubjectHint": "exactly as it appears in titles",
  "knowledge.termMeaningPlaceholder": "Optional — what it is, in a sentence",
  "knowledge.addTermButton": "Add term",
  "knowledge.description": "Description",
  "knowledge.permanent": "Permanent",
  "knowledge.delete": "Forget",
  "knowledge.empty": "Nothing here yet.",
  "data.correctClassification": "Correct classification",
  "data.correctionCopy": "Your correction is saved locally, becomes the authoritative pill result, and is shown to the model as an example when it tags related videos from the same creator. It triggers sanitized subject research only when the type's Research trigger includes corrections.",
  "data.correctTags": "Correct tags",
  "data.correctTagsHint": "select none to record an explicit decline",
  "data.correctionNote": "Optional note",
  "data.correctionNoteHint": "local preference context",
  "data.saveCorrection": "Save correction",
  "data.corrected": "CORRECTED",
  "data.discordLocalOnly": "Discord collects rendered messages from server channels you open in the browser, never direct messages. The collected content stays on this Mac and is never sent to a provider or remote service.",
  "data.unknownDate": "Unknown observation time",
  "data.diagnostics": "Collection diagnostics",
  "data.diagnosticsCopy": "Local pipeline checkpoints only. They never include page text, titles, creators, URLs, or entry IDs.",
  "data.clearDiagnostics": "Clear diagnostics",
  "data.noDiagnostics": "No collection checkpoints yet. Open a supported page to record the next attempt."
});
