window.runListSearchTests = async () => {
  const results=[], q=s=>scope.querySelector(s), wait=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  const check=(ok,label)=>{if(!ok)throw Error(label);results.push('PASS '+label);};
  const type=(input,text)=>{input.focus();input.value=text;input.dispatchEvent(new InputEvent('input',{bubbles:true}));};
  testState.assets.providerProfiles=Array.from({length:8},(_,i)=>({...testState.assets.providerProfiles[0],id:'provider-'+i,name:'Provider '+i}));
  testState.assets.trees[0].nodes=Array.from({length:8},(_,i)=>({id:'node-'+i,name:'Topic '+i,description:'Definition '+i,parentID:i?'node-0':null,positionX:i*180+24,positionY:i*80+24}));
  pushSnapshot();await wait();q('[data-action="openUtilityPanel"]').click();await wait();
  const search=q('[data-vui-search-input="classifier-providers"]');type(search,'PROVIDER 7');search.setSelectionRange(1,3);
  check(testState.assets.providerProfiles.length===8 && q('.provider-panels .provider-panel').parentNode.children.length===1 && q('.provider-panels .provider-panel:not(.vui-search-hidden)').dataset.providerId==='provider-7','provider search renders the matching card without deleting stored profiles');
  testState.issue='Snapshot while searching';pushSnapshot();await wait();
  const restored=q('[data-vui-search-input="classifier-providers"]');
  check(restored.value==='PROVIDER 7' && scope.activeElement===restored && restored.selectionStart===1,'provider search query and caret survive snapshots');
  restored.closest('.vui-search').querySelector('.vui-search-clear').click();await wait();
  const providerType=q('[data-form-id="new-provider-profile-form"] [data-field="type"]');
  providerType.nextElementSibling.querySelector('button').click();await wait();
  const menu=q('.vui-menu'), optionSearch=menu.querySelector('input');
  type(optionSearch,'Reddit');optionSearch.setSelectionRange(1,3);
  check(menu.querySelectorAll('.vui-menu-item').length===1 && providerType.value==='', 'provider-type search leaves the draft selection unchanged');
  testState.issue='Snapshot with dropdown open';pushSnapshot();await wait();
  check(q('.vui-menu input')===optionSearch && optionSearch.value==='Reddit' && scope.activeElement===optionSearch,'open dropdown rebinds to the replacement select and preserves its query and focus');
  q('.vui-menu-item').click();await wait();
  check(q('[data-form-id="new-provider-profile-form"] [data-field="type"]').value==='reddit','choice updates the replacement control, not its detached predecessor');
  q('[data-action="closeUtilityPanel"]').click();await wait();q('[data-action="selectType"]').click();await wait();
  const find=q('[data-vui-search-input="tree:tree-1"]');type(find,'definition 7');await wait();
  const map=q('[data-tree-map]');
  check(map.querySelectorAll('.tree-map-node').length===8 && map.querySelectorAll('.vui-search-match').length===1 && map.scrollLeft>0,'tree search matches descriptions, keeps every branch and pans to the result');
  check(q('.vui-search [role="status"]').textContent.includes('matches'),'tree find reports the result count');
  const count=commands.length;type(find,'Topic');
  find.closest('.vui-search').querySelector('[data-vui-next-match]').click();await wait();
  check(commands.length===count && map.querySelectorAll('.vui-search-match').length===8 && find.closest('.vui-search').querySelector('[role="status"]').textContent.startsWith('2 /'),'next tree match does not edit tags or send native commands');
  find.focus();find.setSelectionRange(1,3);testState.issue='Tree snapshot';pushSnapshot();await wait();
  check(q('[data-vui-search-input="tree:tree-1"]').value==='Topic' && scope.activeElement.dataset.vuiSearchInput==='tree:tree-1','tree query and focus survive a snapshot');
  check(uiErrors.length===0,'search produces no renderer errors');
  return results;
};
