window.runModelPickerTests=async()=>{
  const results=[],q=s=>scope.querySelector(s), wait=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  const expect=(condition,label)=>{if(!condition)throw Error(label);results.push('PASS '+label)};
  const poll=async(predicate)=>{const end=performance.now()+5000;while(!predicate()){if(performance.now()>end)throw Error('Timed out');await new Promise(r=>setTimeout(r,20))}await wait()};
  const change=(selector,value)=>{const c=q(selector);c.value=value;c.dispatchEvent(new Event('change',{bubbles:true}))};
  const form='[data-form-id="utility-research-form"]',count=action=>commands.filter(c=>c.action===action).length;
  await poll(()=>q('[data-action="openUtilityPanel"]'));q('[data-action="openUtilityPanel"]').click();await wait();
  expect(q(form+' [data-field="llmModelIdentifier"]').type==='hidden','model identifier has no free-text entry');
  expect(q('[data-model-fetch]').disabled && q('.research-model-field').textContent.includes('Choose a provider first'),'fetch guides missing provider');
  change(form+' [data-field="llmProviderProfileID"]','provider-1');await wait();
  expect(q('[data-model-fetch]').disabled && q('.research-model-field').textContent.includes('API key'),'fetch guides missing key');
  testState.assets.providerProfiles[0].credential='synthetic-key';testState.assets.providerProfiles[0].hasCredential=true;pushSnapshot();await wait();
  expect(q('[data-model-fetch]').textContent==='Fetch model list' && !q('[data-model-selector]'),'unfetched provider offers Fetch model list');
  expect(count('probeProviderModelCatalog')===0,'opening Settings and choosing a provider do not fetch automatically');
  modelFetchResults['provider-1']=Array.from({length:256},(_,i)=>'model-'+String(i).padStart(3,'0'));
  q('[data-model-fetch]').click();
  expect(q('[data-model-fetch]').disabled && q('[data-model-fetch]').textContent==='Fetching models…','fetch exposes loading state and disables duplicate request');
  q('[data-model-fetch]').click();expect(count('probeProviderModelCatalog')===1,'duplicate click does not fetch twice');
  await poll(()=>q('[data-model-selector]'));
  expect(q('[data-model-selector]').textContent==='Choose a model' && !testState.settings.research.llmModelIdentifier,'fetch does not choose a model');
  expect(!testState.settings.research.enabled && commands.every(c=>c.action!=='testProviderProfile'),'model listing does not enable consent or run a generation test');
  q('[data-model-selector]').click();await wait();
  const list=q('.research-model-list');expect(list.children.length===256 && getComputedStyle(list).overflowY==='auto' && list.scrollHeight>list.clientHeight,'all fetched models remain inside a bounded list');
  list.scrollTop=list.scrollHeight;expect(list.scrollTop>0,'last fetched model is reachable by scrolling');
  const scroll=list.scrollTop;testState.issue='Scroll snapshot';pushSnapshot();await wait();
  expect(Math.abs(q('.research-model-list').scrollTop-scroll)<2,'snapshot preserves the model list scroll');
  const search=q('[data-model-search]');search.focus();search.value='255';search.dispatchEvent(new InputEvent('input',{bubbles:true}));search.setSelectionRange(1,2);
  expect([...q('.research-model-list').children].filter(c=>!c.hidden).length===1,'search filters the full model list');
  testState.issue='Synthetic snapshot';pushSnapshot();await wait();
  expect(q('.research-model-picker').open && scope.activeElement?.matches('[data-model-search]') && scope.activeElement.value==='255' && scope.activeElement.selectionStart===1,'snapshot preserves open picker, search and caret');
  const ime=q('[data-model-search]');ime.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));
  testState.assets.providerModelCatalogs['provider-1'].push('model-255-new');pushSnapshot();
  expect(!q('[data-model-pick="model-255-new"]'),'snapshot waits while model search composition is active');
  ime.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await wait();
  expect(q('[data-model-pick="model-255-new"]') && scope.activeElement?.value==='255','composition end applies the pending catalog without losing search');
  const saves=count('saveResearchSettings');ackDelay=350;q('[data-model-pick="model-255"]').click();await wait();
  expect(q('[data-model-selector]').textContent==='model-255' && !q('.research-model-picker').open,'choice displays immediately and closes the picker');
  await poll(()=>testState.settings.research.llmModelIdentifier==='model-255');await new Promise(r=>setTimeout(r,400));ackDelay=0;
  expect(count('saveResearchSettings')===saves+1 && scope.activeElement?.matches('[data-model-selector]'),'model choice autosaves once and leaves keyboard focus on selector');
  testState.issue=null;modelFetchError='Synthetic model fetch failure';pushSnapshot();await wait();q('[data-model-fetch]').click();
  await poll(()=>q('[data-model-fetch]').textContent==='Retry');
  expect(q('.research-model-field').textContent.includes(modelFetchError) && q('[data-model-pick="model-255"]') && testState.settings.research.llmModelIdentifier==='model-255','failed refresh retains cached list and current choice with Retry');
  modelFetchError=null;modelFetchResults['provider-1']=['replacement-model'];q('[data-model-fetch]').click();await poll(()=>q('[data-model-pick="replacement-model"]'));
  expect(q('[data-model-fetch]').textContent==='Refresh model list' && q('.research-model-unavailable').textContent==='Unavailable in fetched list' && q('[data-model-selector]').textContent==='model-255','successful refresh marks unavailable saved choice without replacing it');
  testState.assets.providerProfiles.push({...testState.assets.providerProfiles[0],id:'provider-2',name:'Second provider'});
  testState.assets.providerModelCatalogs['provider-2']=['second-model'];pushSnapshot();await wait();
  const modelBefore=testState.settings.research.llmModelIdentifier;
  change(form+' [data-field="llmProviderProfileID"]','provider-2');await wait();
  expect(q('[data-model-pick="second-model"]') && !q('[data-model-pick="replacement-model"]') && testState.settings.research.llmModelIdentifier===modelBefore,'provider change shows its own list without choosing a model');
  q('[data-model-selector]').click();await wait();
  const query=q('[data-model-search]');query.value='does-not-exist';query.dispatchEvent(new InputEvent('input',{bubbles:true}));
  expect(!q('[data-model-no-matches]').hidden && q('[data-model-pick="second-model"]').hidden,'search exposes an empty result state');
  query.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));expect(!q('.research-model-picker').open && q('.utility-popover'),'Escape closes the picker first');
  q('[data-model-selector]').click();await wait();q('[data-model-search]').value='';q('[data-model-search]').dispatchEvent(new InputEvent('input',{bubbles:true}));
  expect(q('.utility-popover').scrollWidth<=q('.utility-popover').clientWidth+1,'model picker fits viewport width');
  expect(uiErrors.length===0,'no renderer exceptions');
  q('.research-model-field').scrollIntoView({block:'center'});await wait();
  return results;
};
