window.runResearchSetupTests=async()=>{
  const results=[],q=s=>scope.querySelector(s), wait=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  const expect=(condition,label)=>{if(!condition)throw Error(label);results.push('PASS '+label)};
  const poll=async(predicate)=>{const end=performance.now()+5000;while(!predicate()){if(performance.now()>end)throw Error('Timed out');await new Promise(r=>setTimeout(r,20))}await wait()};
  const change=(selector,value)=>{const control=q(selector);if(!control)throw Error('Missing '+selector);control.value=value;control.dispatchEvent(new Event('change',{bubbles:true}))};
  const choice='[data-group-research-choice]',research='[data-form-id="utility-research-form"]';
  const groupSaves=()=>commands.filter(c=>c.action==='saveClassifierTypeResearch').length;
  const close=()=>q('[data-action="closeUtilityPanel"]').click();
  const focused=(field)=>(scope.activeElement?.dataset.field || scope.activeElement?.closest('.field')?.querySelector('select')?.dataset.field)===field;
  const onLabel=()=>q(choice).querySelector('option[value="on"]').textContent;
  await poll(()=>q('[data-action="selectType"]'));q('[data-action="selectType"]').click();await wait();
  expect(!q('[data-workspace="llmAssist"]'),'API keys removed from sidebar');
  expect(onLabel()==='Set up grounded research…','missing configuration replaces On with setup');
  q(choice).nextElementSibling.querySelector('.vui-select-button').click();
  [...document.querySelectorAll('.vui-menu-item')].find(item=>item.textContent==='Set up grounded research…').click();await wait();
  expect(groupSaves()===0 && q(choice).value==='inherit','setup preserves group choice without autosaving On');
  expect(focused('llmProviderProfileID'),'setup focuses the provider selector');
  expect(q('.utility-api-keys').nextElementSibling.matches('.utility-research-section'),'API keys are immediately above grounded research in Settings');
  expect(!testState.settings.research.enabled,'setup does not enable global consent');
  change(research+' [data-field="llmProviderProfileID"]','provider-1');await poll(()=>testState.settings.research.llmProviderProfileID==='provider-1');
  close();change(choice,'on');await wait();
  expect(focused('credential') && q('.research-setup-needed [data-field="credential"]'),'selected provider with no key focuses and highlights its key');
  const popover=q('.utility-popover'),scroll=popover.scrollTop;
  const key=q('[data-provider-id="provider-1"] [data-field="credential"]');key.focus();key.value='synthetic-key';key.dispatchEvent(new InputEvent('input',{bubbles:true}));
  await poll(()=>testState.assets.providerProfiles[0].credential==='synthetic-key');
  expect(Math.abs(q('.utility-popover').scrollTop-scroll)<3 && focused('credential'),'key autosave preserves Settings scroll and focus');
  close();change(choice,'on');await wait();expect(scope.activeElement?.matches('[data-model-fetch]'),'key present but model missing focuses Fetch model list');
  q('[data-model-fetch]').click();await poll(()=>q('[data-model-selector]'));q('[data-model-selector]').click();q('[data-model-pick="test-grounded-model"]').click();await poll(()=>testState.settings.research.llmModelIdentifier==='test-grounded-model');
  close();expect(onLabel()==='Enable grounded research…','configured provider replaces On with enable when consent is off');
  change(choice,'on');await wait();expect(focused('enabled') && groupSaves()===0,'enable opens global consent without saving group On');
  const consent=q(research+' [data-field="enabled"]');consent.checked=true;consent.dispatchEvent(new Event('change',{bubbles:true}));
  await poll(()=>testState.settings.research.enabled);close();expect(onLabel()==='On','acknowledged configuration and consent restore On');
  expect(testState.assets.classifierTypes[0].researchEnabled===null,'finishing setup keeps the existing group choice');
  change(choice,'on');await poll(()=>testState.assets.classifierTypes[0].researchEnabled===true);expect(groupSaves()===1,'ready On autosaves normally');
  change(choice,'off');await poll(()=>testState.assets.classifierTypes[0].researchEnabled===false);
  change(choice,'inherit');await poll(()=>testState.assets.classifierTypes[0].researchEnabled===null);
  expect(groupSaves()===3,'Off and Follow global switch still autosave');
  q('[data-action="workspace"][data-workspace="knowledge"]').click();await wait();
  expect(q('.knowledge-research-connection').textContent.includes('Test provider') && q('.knowledge-research-connection').textContent.includes('test-grounded-model'),'Knowledge identifies its provider and model');
  testState.settings.research.enabled=false;pushSnapshot();await wait();
  expect(q('[data-action="openResearchSetup"]').textContent==='Enable grounded research…','Knowledge reports disabled consent');
  q('[data-action="openResearchSetup"]').click();await wait();expect(focused('enabled'),'Knowledge link opens the same Settings consent');close();
  testState.assets.providerProfiles=[];pushSnapshot();await wait();
  q('[data-action="openResearchSetup"]').click();await wait();expect(focused('type'),'deleted provider opens API key creation safely');
  change('[data-form-id="new-provider-profile-form"] [data-field="type"]','openAI');q('[data-action="createProviderProfile"]').click();await poll(()=>q('[data-provider-id="provider-created"]'));
  expect(!!q('[data-provider-id="provider-created"]'),'provider creation remains available in Settings');
  close();testState.workspace='llmAssist';pushSnapshot();await wait();
  expect(q('.editor-panel').dataset.workspace==='browserBridge' && !q('.provider-workspace'),'retired workspace snapshot safely returns to groups');
  q('[data-action="selectType"]').click();
  testState.settings.research.llmProviderProfileID='provider-created';testState.assets.providerProfiles[0].credential='   ';pushSnapshot();await wait();
  expect(onLabel()==='Set up grounded research…','whitespace credential is treated as missing');
  q('[data-action="workspace"][data-workspace="knowledge"]').click();q('[data-action="openResearchSetup"]').click();await wait();
  expect(uiErrors.length===0,'no renderer exceptions');
  expect(q('.utility-popover').scrollWidth<=q('.utility-popover').clientWidth+1,'setup fits viewport width');
  return results;
};
