window.runTagBoundsTests=async()=>{
  const results=[],q=s=>scope.querySelector(s);
  const expect=(c,label)=>{if(!c)throw Error(label);results.push('PASS '+label)};
  const poll=async(fn)=>{const until=performance.now()+5000;while(!fn()){if(performance.now()>until)throw Error('Timed out');await new Promise(r=>setTimeout(r,20))}};
  const tick=()=>new Promise(r=>setTimeout(r,360));
  const form='[data-form-id="classifier-local-model-form-group-1"]';
  const minimum=form+' [data-field="minimumTagsOverride"]',maximum=form+' [data-field="maximumTagsOverride"]';
  const input=(selector,value)=>{const c=q(selector);c.focus();c.value=value;c.dispatchEvent(new InputEvent('input',{bubbles:true}));};
  const dial=position=>{const c=q(form+' [data-field="strictness"][value="'+position+'"]');c.checked=true;c.dispatchEvent(new Event('change',{bubbles:true}));};
  const saves=()=>commands.filter(c=>c.action==='saveClassifierTypeLocalModel').length;
  const model=()=>testState.assets.classifierTypes[0].localModel;
  await poll(()=>q('[data-action="selectType"]'));q('[data-action="selectType"]').click();
  const more='[data-expand="type-more:group-1"]';
  expect(!q(more).open && q(form+' [data-field="houseRules"]').checkVisibility()
    && q(form+' .dial-card-grid').checkVisibility() && q('[data-group-research-choice]').nextElementSibling?.checkVisibility(),'core model, rules and research settings stay visible outside More');
  q(more+' summary').click();
  expect(q(minimum).value==='' && q(maximum).value==='' && q(minimum).placeholder==='0' && q(maximum).placeholder==='3','empty bounds display the selected dial defaults');
  input(minimum,'1');await poll(()=>model().minimumTagsOverride===1);
  input(maximum,'2');await poll(()=>model().maximumTagsOverride===2);
  expect(model().minimumTagsOverride===1 && q(more+' summary').textContent.includes('1–2'),'tag counts autosave and remain visible in collapsed summary');
  dial(1);await poll(()=>model().strictness===1);
  expect(model().maximumTagsOverride===2 && model().minimumTagsOverride===1,'changing the dial preserves explicit bounds');
  input(minimum,'');await poll(()=>model().minimumTagsOverride===null);
  expect(model().maximumTagsOverride===2 && q(minimum).placeholder==='0','clearing minimum follows only its dial default');
  dial(5);await poll(()=>model().strictness===5);
  input(maximum,'');await poll(()=>model().maximumTagsOverride===null);
  expect(q(minimum).placeholder==='1' && q(maximum).placeholder==='3','both blank bounds track a different dial position');
  input(minimum,'2');await poll(()=>model().minimumTagsOverride===2);
  let before=saves();input(maximum,'1');await tick();
  expect(saves()===before && !q('[data-tag-bounds-error]').hidden && model().maximumTagsOverride===null,'minimum above effective maximum shows an error and does not save');
  input(maximum,'3');await poll(()=>model().maximumTagsOverride===3);
  expect(q('[data-tag-bounds-error]').hidden && model().minimumTagsOverride===2,'fixing the pair saves both bounds together');
  before=saves();input(minimum,'1.5');await tick();
  expect(saves()===before && !q('[data-tag-bounds-error]').hidden,'fractional tag counts are rejected');
  ackDelay=450;input(minimum,'3');pushSnapshot();
  expect(q(minimum).value==='3' && scope.activeElement===q(minimum),'tag-count draft and focus survive incoming snapshots');
  await poll(()=>model().minimumTagsOverride===3);await new Promise(r=>setTimeout(r,500));ackDelay=0;
  q(more+' summary').click();pushSnapshot();
  expect(!q(more).open && q(more+' summary').textContent.includes('3–3'),'collapsed More preserves its custom tag-count summary through snapshots');
  testState.assets.classifierTypes.push({id:'group-2',name:'Other group',treeID:'tree-1',applicablePlatformIDs:['reddit'],localModel:{speedQuality:'balanced',strictness:3,houseRules:''},researchEnabled:null,order:1});pushSnapshot();
  q('[data-action="selectType"][data-type-id="group-2"]').click();q('[data-expand="type-more:group-2"] summary').click();
  expect(q('[data-form-id="classifier-local-model-form-group-2"] [data-field="minimumTagsOverride"]').value==='' && model().minimumTagsOverride===3,'another group keeps its own blank bounds');
  expect(uiErrors.length===0,'no renderer errors');
  return results;
};
