window.VaultClassifierStrings = Object.freeze({
  "app.title": "Vault Classifier",
  "app.loading": "Loading the local Vault Classifier shell…",
  "hero.offline": "OFFLINE ON THIS MAC",
  "utility.close": "Close",
  "utility.settings.button": "Settings",
  "utility.settings.title": "Local settings",
  "utility.settings.copy": "Choose the resource limits and explicit local work this Mac is allowed to perform.",
  "language.label": "Language",
  "language.name.en": "English",
  "language.name.ar": "العربية",
  "language.name.bn": "বাংলা",
  "language.name.de": "Deutsch",
  "language.name.es": "Español",
  "language.name.fr": "Français",
  "language.name.hi": "हिन्दी",
  "language.name.id": "Bahasa Indonesia",
  "language.name.it": "Italiano",
  "language.name.ja": "日本語",
  "language.name.ko": "한국어",
  "language.name.nl": "Nederlands",
  "language.name.pa": "ਪੰਜਾਬੀ",
  "language.name.pl": "Polski",
  "language.name.pt": "Português",
  "language.name.ru": "Русский",
  "language.name.th": "ไทย",
  "language.name.tr": "Türkçe",
  "language.name.vi": "Tiếng Việt",
  "language.name.zh": "中文",
  "navigation.aria": "Classifier workspaces",
  "navigation.resize": "Resize classifier navigation",
  "navigation.title": "Classifier work",
  "navigation.subtitle": "Local development shell",
  "navigation.work": "WORK",
  "navigation.control": "CONTROL",
  "navigation.inspect": "Inspect entry",
  "navigation.inspectMeta": "Local decision",
  "navigation.policies": "Named policies",
  "navigation.policiesMeta": "Allow · dim · block",
  "navigation.activity": "Local activity",
  "navigation.activityMeta": "Cache and ledger",
  "navigation.training": "Local training",
  "navigation.trainingMeta": "Explicit labels",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.audit": "Personal audit",
  "navigation.auditMeta": "Optional Gemini review",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.profile.light": "Light",
  "enum.profile.balanced": "Balanced",
  "enum.profile.aggressive": "Aggressive",
  "enum.update.automatic": "Automatic",
  "enum.update.downloadThenAsk": "Ask first",
  "enum.update.manual": "Manual",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "inspect.title": "Inspect an entry",
  "inspect.copy": "Provide the same compact evidence a browser adapter will send. The classifier derives ancestors locally.",
  "inspect.feedDecision": "FEED DECISION",
  "inspect.pageDecision": "PAGE DECISION",
  "inspect.entryTitle": "ENTRY TITLE",
  "inspect.required": "Required",
  "inspect.sourceID": "SOURCE ID",
  "inspect.optional": "Optional",
  "inspect.platform": "CLASSIFICATION PLATFORM",
  "inspect.platformCopy": "Uses this platform's active classifier type",
  "inspect.surface": "TARGET SURFACE",
  "inspect.surfaceHint": "Feed is +5% stricter",
  "inspect.classify": "Classify locally",
  "inspect.localOnly": "No upload · no provider key · local ledger",
  "inspect.classifyWithLLM": "Ask configured LLM",
  "inspect.llmClassifying": "Classifying…",
  "inspect.llmExplicitOnly": "Explicit manual request · sends this entry only to the attached provider · suggestion stays pending review",
  "inspect.noResult": "No local result yet. Classify an entry to inspect the decision and candidate tags.",
  "inspect.noLeaf": "No leaf met the current local threshold.",
  "inspect.noPolicy": "No active policy matched this entry.",
  "inspect.markFalseAllow": "Mark false allow",
  "inspect.markFalseDim": "Mark false dim",
  "inspect.markFalseBlock": "Mark false block",
  "inspect.policyDecision": "POLICY DECISION",
  "inspect.threshold": "threshold {value}",
  "inspect.predictedLeaves": "PREDICTED LEAVES",
  "inspect.ancestorsComputed": "Ancestors are computed",
  "inspect.localScores": "STRONGEST LOCAL SCORES",
  "inspect.sourcePrior": "Direct + eligible source prior",
  "inspect.policyMatches": "POLICY MATCHES",
  "inspect.computedPath": "Computed path: {path}",
  "policies.title": "Named policies",
  "policies.copy": "Policies live in Vault Classifier. A browser can only ask for a policy ID and render the returned decision.",
  "policies.savedCount": "{count} SAVED",
  "policies.saved": "Saved policies",
  "policies.savedCopy": "Select a policy to edit its local criteria.",
  "policies.new": "New policy",
  "policies.empty": "No named policies are saved. Create one to classify against local criteria.",
  "policies.edit": "Edit policy",
  "policies.create": "Create a policy",
  "policies.editorCopy": "Exact tag IDs are validated locally before the policy is saved.",
  "policies.id": "POLICY ID",
  "policies.idHint": "Letters, numbers, . _ -",
  "policies.displayName": "DISPLAY NAME",
  "policies.localOnly": "Local only",
  "policies.includeAny": "INCLUDE ANY TAGS",
  "policies.exactIDs": "Comma separated exact tag IDs",
  "policies.exclude": "EXCLUDE TAGS",
  "policies.feedAction": "FEED ACTION",
  "policies.feedHint": "Default is dim",
  "policies.pageAction": "PAGE ACTION",
  "policies.pageHint": "Page dim becomes block",
  "policies.save": "Save locally",
  "common.delete": "Delete",
  "activity.title": "Local activity",
  "activity.copy": "The bounded cache and decision ledger stay on this Mac. Viewing content is never a training label.",
  "activity.localOnly": "LOCAL ONLY",
  "activity.cache": "CACHE",
  "activity.ledger": "LEDGER",
  "activity.corrections": "CORRECTIONS",
  "activity.resources": "Resource controls",
  "activity.resourcesCopy": "Preferences only: this development build has no endpoint or automatic task.",
  "activity.profile": "RESOURCE PROFILE",
  "activity.profileHint": "Local capacity default",
  "activity.cacheCapacity": "CACHE CAPACITY",
  "activity.uniqueEntries": "Unique entries",
  "activity.packageUpdates": "PACKAGE UPDATES",
  "activity.preference": "Local preference",
  "activity.idleWork": "Allow low-priority cache refresh work",
  "activity.backgroundSync": "Allow daily package checks when an endpoint is configured",
  "activity.auditDispatch": "Allow personal LLM audit dispatch",
  "activity.save": "Save local resource settings",
  "activity.recent": "Recent decisions",
  "activity.newest": "Newest first.",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "activity.empty": "No local decisions yet. Inspect an entry to create the first ledger record.",
  "training.title": "Local training",
  "training.copy": "Rebuild a bounded correction layer only from labels you explicitly store. Views, clicks, raw corrections, and provider output alone are never labels.",
  "training.localOnly": "LOCAL ONLY",
  "training.noLabels": "NO LABELS",
  "training.labels": "EXPLICIT LABELS",
  "training.features": "MODEL FEATURES",
  "training.lastRebuild": "LAST REBUILD",
  "training.notYet": "Not yet",
  "training.labelCount": "{count} labels",
  "training.currentLabel": "Current entry label",
  "training.currentLabelCopy": "Classify an entry first, then explicitly describe predictable leaf tags. Parent nodes are computed locally.",
  "training.positive": "POSITIVE LEAF TAGS",
  "training.negative": "NEGATIVE LEAF TAGS",
  "training.commaSeparated": "Comma separated",
  "training.optionalCommaSeparated": "Optional, comma separated",
  "training.store": "Store current label",
  "training.replace": "A new label for the same source entry replaces its prior local label.",
  "training.rebuild": "Rebuild correction layer",
  "training.rebuildCopy": "This deterministic local run affects new classifications only.",
  "training.passes": "PASSES",
  "training.passesHint": "1–12",
  "training.localAction": "LOCAL ACTION",
  "training.retrain": "Retrain local model",
  "training.lastRun": "Last rebuild: {labels} labels · {updates} updates · {epochs} passes · taxonomy {taxonomy}",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this Mac's package, explicit training corpus, policies, and correction layer. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in this Mac's Keychain. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "OWNER CODE",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current model snapshot plus three previous snapshots. Browsing cache, decision ledger, and audit history are excluded.",
  "backup.localFolder": "LOCAL FOLDER",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after every successful local model rebuild",
  "backup.save": "Save backup mode",
  "backup.create": "Create backup now",
  "audit.title": "Personal audit",
  "audit.copy": "Optional review of potential false allows. A provider call happens only after an explicit button press and a conservative local token reservation.",
  "audit.resourceHold": "RESOURCE HOLD",
  "audit.keyNeeded": "KEY NEEDED",
  "audit.ready": "READY",
  "audit.settings": "Local audit settings",
  "audit.settingsCopy": "The only fixed adapter in this development slice is Gemini. No arbitrary endpoint can be entered here.",
  "audit.enable": "Enable personal local auditing",
  "audit.provider": "APPROVED PROVIDER",
  "audit.fixedAdapter": "Fixed adapter",
  "audit.gemini": "Gemini",
  "audit.reasoning": "REASONING",
  "audit.perRequest": "Per request",
  "audit.model": "MODEL IDENTIFIER",
  "audit.modelHint": "Validated before any request",
  "audit.selection": "SELECTION",
  "audit.selectionHint": "Local only",
  "audit.outputCap": "MAX OUTPUT TOKENS",
  "audit.outputHint": "2,048 max",
  "audit.requestCap": "PER REQUEST",
  "audit.reservation": "Local reservation",
  "audit.weekly": "WEEKLY",
  "audit.accounting": "Local accounting",
  "audit.monthly": "MONTHLY",
  "audit.polish": "Use confirmed audit labels only to polish this Mac's personal model",
  "audit.save": "Save local audit settings",
  "audit.dispatchHeld": "Resource controls currently prevent Gemini dispatch. Enable Personal LLM audit dispatch in Local activity before a queued item can spend tokens.",
  "audit.key": "Gemini API key",
  "audit.keyCopy": "Keychain only. The extension, shared local bridge, state file, diagnostics, and server never receive this credential.",
  "audit.keychain": "KEYCHAIN CREDENTIAL",
  "audit.replaceHint": "Enter a replacement",
  "audit.keyHint": "Paste a Gemini API key",
  "audit.replace": "Replace",
  "audit.store": "Store",
  "audit.remove": "Remove",
  "audit.queueRisk": "Queue risk-selected allows",
  "audit.queueCurrent": "Queue current entry for review",
  "audit.copyDiagnostics": "Copy redacted diagnostics",
  "audit.queued": "QUEUED",
  "audit.settled": "SETTLED",
  "audit.inFlight": "IN FLIGHT",
  "audit.uncertain": "UNCERTAIN",
  "audit.weeklyTokens": "WEEKLY TOKENS",
  "audit.monthlyTokens": "MONTHLY TOKENS",
  "audit.queue": "Local audit queue",
  "audit.queueCopy": "No evidence leaves this Mac until you explicitly run a configured adapter.",
  "audit.risk": "Risk {value}",
  "audit.eligible": "ELIGIBLE",
  "audit.held": "HELD",
  "audit.running": "Running…",
  "audit.run": "Run Gemini",
  "audit.emptyQueue": "No local audit candidates are queued.",
  "audit.results": "Local audit results",
  "audit.resultsCopy": "Provider output is only a local review suggestion and never trains automatically.",
  "audit.noLeaf": "No returned leaf tags",
  "audit.tokens": "{count} tokens",
  "audit.confirm": "I confirm this false allow:",
  "audit.polishPolicy": "Polish {policy}",
  "audit.emptyResults": "No local audit results yet.",
  "integration.title": "Browser bridge",
  "integration.copy": "The source-only Chrome and Edge adapter remains deliberately unregistered and disabled.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Shared broker",
  "integration.keychain": "No pairing key",
  "integration.host": "Desktop connection",
  "integration.notRegistered": "Connects when available",
  "integration.server": "Broker",
  "integration.notRequired": "Ephemeral",
  "integration.notice": "A signed installer must later supply stable extension IDs and the host path. Until then, Chrome and Edge fail open rather than applying a rule.",
  "navigation.tagTree": "Tag tree",
  "navigation.tagTreeMeta": "Shared tree library",
  "navigation.localModel": "Local model",
  "navigation.localModelMeta": "Train and recover",
  "navigation.llmAssist": "LLM assist",
  "navigation.llmAssistMeta": "Credential profiles",
  "navigation.browserBridge": "Classifier Type",
  "navigation.browserBridgeMeta": "Decision brains",
  "navigation.classificationData": "Classification data",
  "navigation.classificationDataMeta": "Manual and LLM records",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.title": "Tag tree",
  "tree.copy": "Create and evolve reusable local tag trees. Every edit publishes a revision before a compatible model can train.",
  "tree.sharedLibrary": "SHARED LIBRARY",
  "tree.active": "Active tree",
  "tree.activeCopy": "Current local revision {revision}",
  "tree.inspector": "NODE INSPECTOR",
  "tree.inspectorCopy": "Changes publish a new tree revision and make the previous model incompatible until retraining finishes.",
  "tree.activeNode": "ACTIVE",
  "tree.nodeName": "NODE NAME",
  "tree.level": "Level {value}",
  "tree.rootNode": "Root node",
  "tree.childOf": "Child of {name}",
  "tree.nodeCount": "{count} nodes",
  "tree.panel": "TREE PANEL",
  "tree.multiplePanels": "Each tree keeps its own editing panel.",
  "tree.contextHint": "Click or right-click to edit this node",
  "tree.saveNode": "Save node",
  "tree.createNode": "Create node",
  "tree.editNode": "Edit node",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a node to make it the parent.",
  "tree.connection": "Connection",
  "tree.disconnection": "Disconnection",
  "tree.deleteNode": "Delete node",
  "tree.rename": "Rename",
  "tree.renameTree": "Rename tree",
  "tree.saveTreeName": "Save tree",
  "tree.rearrange": "Rearrange",
  "tree.delete": "Delete",
  "tree.confirmDelete": "Delete tree?",
  "tree.confirmDeleteCopy": "This permanently removes the tree, its dependent local models, and any platform link to it.",
  "tree.confirmDeleteAction": "Delete tree",
  "tree.canvasHint": "Right-click empty space to create a root node. Click or right-click a node to edit it. Drag a node to reposition its branch.",
  "tree.empty": "No nodes are in this local tree yet.",
  "tree.addTag": "Add a tag",
  "tree.addCopy": "Tags stay local. Adding a node creates a new tree revision.",
  "tree.tagName": "TAG NAME",
  "tree.add": "Add local tag",
  "tree.newTree": "New tag tree",
  "tree.newCopy": "A new tree is a reusable library asset. Bind it deliberately to a browser platform.",
  "tree.treeName": "TREE NAME",
  "tree.create": "Create tree",
  "model.title": "Local model",
  "model.copy": "Build local text-embedding and neural-classifier assets from the tree and approved classification data you choose.",
  "model.sharedLibrary": "SHARED LIBRARY",
  "model.multiplePanels": "Each local model keeps its own training panel.",
  "model.newModel": "New local model",
  "model.modelName": "MODEL NAME",
  "model.create": "Create model",
  "model.panel": "MODEL PANEL",
  "model.version": "Version {value}",
  "model.rename": "Rename model",
  "model.delete": "Delete model",
  "model.confirmDelete": "Delete this local model?",
  "model.confirmDeleteCopy": "This removes its stored neural artifact and cannot be undone.",
  "model.setup": "Model setup",
  "model.setupCopy": "Choose the exact local assets this model will train against. Changing setup clears its trained artifact.",
  "model.targetTree": "TARGET TREE",
  "model.classificationPlatforms": "CLASSIFICATION-DATA SOURCES",
  "model.classificationPlatformsCopy": "Choose one or more compatible platforms to train together.",
  "model.baseLanguageModel": "BASE LANGUAGE MODEL",
  "model.baseCopy": "Optional package selection. This build trains the compact local embedding until a selected package is downloaded and activated.",
  "model.base.none": "None · compact local embedding",
  "model.base.allMiniLML6V2": "all-MiniLM-L6-v2",
  "model.base.allMPNetBaseV2": "all-mpnet-base-v2",
  "model.base.multilingualE5Small": "multilingual-e5-small",
  "model.base.multilingualE5Base": "multilingual-e5-base",
  "model.base.multilingualE5Large": "multilingual-e5-large",
  "model.base.bgeM3": "bge-m3",
  "model.trainingScope": "{records} approved records · {tags} available tags",
  "model.train": "Train local model",
  "model.trainedRun": "Trained from {records} records · {updates} label updates · {epochs} passes",
  "model.untrained": "Set up this model, then run an explicit local training pass.",
  "model.empty": "No local model assets yet. Create one to choose its tree, data sources, base model, and explicit training run.",
  "model.ready": "READY",
  "model.needsTraining": "NEEDS TRAINING",
  "model.models": "MODELS",
  "model.labels": "APPROVED LABELS",
  "model.versions": "VERSION",
  "model.active": "Active compatible model",
  "model.activeCopy": "A platform may activate one model whose tree and dataset revisions exactly match.",
  "model.none": "No local model",
  "model.boundRevisions": "Tree r{tree} · Data r{data}",
  "model.localTraining": "Explicit local training",
  "model.trainingCopy": "Training is user-controlled local work. Browsing-time inference remains fast and local.",
  "model.passes": "TRAINING PASSES",
  "model.explicitAction": "LOCAL ACTION",
  "model.backup": "Advanced backup",
  "model.backupCopy": "Optional local snapshots are owner-code gated and never leave this Mac.",
  "model.advanced": "Backup settings",
  "model.backupStatus": "Latest plus {count} previous snapshots",
  "llm.title": "LLM assist",
  "llm.copy": "Create local language-model or blockable-platform data profiles. An activated classifier type processes eligible collected creators one at a time.",
  "llm.keyLibrary": "KEY LIBRARY",
  "llm.providerType": "PROVIDER TYPE",
  "llm.createKey": "Create key",
  "llm.createCopy": "Use a direct common-model preset, a blockable-platform data API profile, or OpenAI-compatible / Custom for another compatible HTTPS endpoint.",
  "llm.empty": "No API-key profiles yet. Choose a provider type, then create its local setup panel.",
  "llm.providerPanel": "PROVIDER PANEL",
  "llm.provider.openAI": "OpenAI",
  "llm.provider.openAICompatible": "OpenAI-compatible API",
  "llm.provider.deepSeek": "DeepSeek",
  "llm.provider.gemini": "Gemini",
  "llm.provider.anthropic": "Anthropic",
  "llm.provider.mistral": "Mistral AI",
  "llm.provider.cohere": "Cohere",
  "llm.provider.groq": "Groq",
  "llm.provider.openRouter": "OpenRouter",
  "llm.provider.ollama": "Ollama",
  "llm.provider.youtubeData": "YouTube Data API",
  "llm.provider.twitch": "Twitch",
  "llm.provider.reddit": "Reddit",
  "llm.provider.xPlatform": "X API",
  "llm.provider.tikTok": "TikTok",
  "llm.provider.instagramGraph": "Instagram Graph API",
  "llm.provider.facebookGraph": "Facebook Graph API",
  "llm.provider.custom": "Custom API",
  "llm.providerGroup.models": "LANGUAGE MODELS",
  "llm.providerGroup.platform": "BLOCKABLE PLATFORM DATA APIs",
  "llm.providerGroup.custom": "CUSTOM AND COMPATIBLE APIs",
  "llm.deleteProfile": "Delete profile",
  "llm.apiKeyOrToken": "API KEY OR TOKEN",
  "llm.apiEndpoint": "API ENDPOINT",
  "llm.testModel": "MODEL FOR TEST",
  "llm.replaceCredential": "A credential is stored — enter a replacement",
  "llm.test": "Test request",
  "llm.testing": "Testing…",
  "llm.tokenUsage": "TOKEN USAGE",
  "llm.tokenTotals": "Input {input} · Output {output}",
  "llm.protocol.accountID": "ACCOUNT ID",
  "llm.protocol.apiVersion": "API VERSION",
  "llm.protocol.clientID": "CLIENT ID",
  "llm.protocol.location": "LOCATION",
  "llm.protocol.projectID": "PROJECT ID",
  "llm.protocol.region": "REGION",
  "llm.protocol.userAgent": "USER AGENT",
  "llm.protocol.searchEngineID": "SEARCH ENGINE ID",
  "llm.protocol.protocolFamily": "REQUEST FAMILY",
  "bridge.title": "Classifier Type",
  "bridge.copy": "Build local decision brains from matching trees, data, models, and explicit LLM assist profiles. Browser connection controls live in Settings.",
  "bridge.typeLibrary": "DECISION BRAIN LIBRARY",
  "bridge.typePanel": "CLASSIFIER TYPE",
  "bridge.newTypeName": "NEW CLASSIFIER TYPE",
  "bridge.newTypeNameCopy": "For example, YouTube creator focus",
  "bridge.createType": "Create type",
  "bridge.emptyTypes": "Create a classifier type to assemble a local decision brain.",
  "bridge.typeName": "TYPE NAME",
  "bridge.saveType": "Save type",
  "bridge.deleteType": "Delete type",
  "bridge.typeMatchCopy": "Tag tree: {tree} · Local data: {data}",
  "bridge.missingAsset": "Missing asset",
  "bridge.configured": "CONFIGURED",
  "bridge.needsSource": "NEEDS SOURCE",
  "bridge.assetSelectionCopy": "Choose one platform. Its platform binding supplies this type's tag tree and collected classification data.",
  "bridge.applicablePlatform": "APPLICABLE PLATFORM",
  "bridge.applicablePlatformCopy": "Only one platform can be used by a classifier type.",
  "bridge.noApplicablePlatform": "Choose a platform",
  "bridge.platformDataChoose": "Choose a platform to bind its local classification data.",
  "bridge.platformDataAutoCreate": "adds local data",
  "bridge.platformDataWillCreate": "Local classification data for {platform} will be added when you save this type.",
  "bridge.platformDataBound": "Local API credential bound: {profile}",
  "bridge.platformDataMissingKey": "No local {platform} API credential is configured.",
  "bridge.platformDataUnavailable": "{platform} has no local API adapter yet.",
  "bridge.manualOnly": "Manual only",
  "bridge.manualOnlyCopy": "Twitch, Reddit, and Discord keep normal manual collection and tagging, but Local model and LLM Assist are unavailable for this classifier type.",
  "bridge.localModel": "LOCAL MODEL",
  "bridge.localModelCopy": "Only ready models matching the selected tree and data are available.",
  "bridge.noLocalModel": "No local model",
  "bridge.sourceKind.creator": "creator",
  "bridge.sourceKind.creatorPlural": "creators",
  "bridge.sourceKind.account": "account",
  "bridge.sourceKind.accountPlural": "accounts",
  "bridge.sourceKind.subreddit": "subreddit",
  "bridge.sourceKind.subredditPlural": "subreddits",
  "bridge.sourceKind.server": "Discord server",
  "bridge.sourceKind.serverPlural": "Discord servers",
  "bridge.manualSource": "Manual {source} classification",
  "bridge.manualSourceCopy": "Choose one active leaf tag and record an independent tagged or not-tagged decision for this {source}. A decision for one tag never decides another tag.",
  "bridge.sourceCount": "{count} {sources}",
  "bridge.sourceTagEmpty": "No {sources} in this section yet.",
  "bridge.sourceDecisionList": "{source} decisions",
  "bridge.sourceDecisionListCopy": "Human and LLM tags are shown together for every collected {sources}.",
  "bridge.sourceClassified": "classified",
  "bridge.source": "COLLECTION SOURCE",
  "bridge.sourceCopy": "Collected under this type's classification data",
  "bridge.classifySourceWithLLM": "Ask LLM to classify {source}",
  "bridge.sourceLLMClassifying": "Classifying source…",
  "bridge.sourceLLMExplicitOnly": "Manual run only while this model is inactive · a valid response becomes this classifier type's approved {source} decision and compatible local-model training data.",
  "bridge.noSources": "Collect public entries first. Their {sources} will appear here for manual classification.",
  "bridge.creatorTagNavigation": "Active leaf tags",
  "bridge.creatorTagNeedDecision": "Need decision",
  "bridge.creatorTagTagged": "Tagged as {tag}",
  "bridge.creatorTagNotTagged": "Not tagged as {tag}",
  "bridge.creatorTagTag": "Tag as {tag}",
  "bridge.creatorTagMarkNot": "Not {tag}",
  "bridge.creatorTagClear": "Clear {tag}",
  "bridge.creatorSubscribers": "{count} subscribers",
  "bridge.creatorAvatarBackfill": "Collect missing icons",
  "bridge.creatorAvatarBackfillCopy": "Visits saved public creator pages and retains only approved profile images.",
  "bridge.creatorAvatarBackfillRunning": "Collecting icons…",
  "bridge.creatorAvatarBackfillComplete": "{count} icon URLs found.",
  "bridge.creatorTags": "ACTIVE LEAF TAGS",
  "bridge.creatorTagsCopy": "Choose one or more tags",
  "bridge.classifyCreator": "Save creator classification",
  "bridge.classifyCreatorBatch": "Classify next {count}",
  "bridge.noCreatorTags": "Add active leaf tags to the selected tag tree before classifying creators.",
  "bridge.llmAssist": "LLM ASSIST",
  "bridge.llmAssistCopy": "Select exactly one provider connection and one model. Activate it to classify complete collected creators sequentially; the secure connection cannot change this type's decision policy.",
  "bridge.llmActivate": "Activate",
  "bridge.llmDeactivate": "Deactivate",
  "bridge.llmActive": "ACTIVE · New complete creators are classified sequentially.",
  "bridge.llmInactive": "INACTIVE · Save a model, then activate it to begin classification.",
  "bridge.llmActivationRunning": "ACTIVE · Classifying creators sequentially…",
  "bridge.noLLMProfiles": "Create an LLM Assist profile before attaching it here.",
  "bridge.noLLMModel": "No LLM model",
  "bridge.llmProvider": "LOCAL PROVIDER CONNECTION",
  "bridge.llmProviderCopy": "The API key stays on this Mac. It grants no model, platform, or decision policy by itself.",
  "bridge.llmModel": "MODEL IDENTIFIER",
  "bridge.llmModelCopy": "Exactly one fetched model is active for this classifier type.",
  "bridge.llmChooseProviderFirst": "Choose a provider connection before selecting its model.",
  "bridge.llmChooseModel": "Choose a fetched model",
  "bridge.llmFetchModels": "Fetch models",
  "bridge.llmLoadingModels": "Fetching models…",
  "bridge.llmFetchModelsCopy": "Fetch the models available from this Custom or compatible API connection.",
  "bridge.llmFixedModelsAtLaunch": "This fixed-provider model list is loaded from the Vault server when Vault Classifier opens.",
  "bridge.llmDailyOutputBudget": "DAILY OUTPUT TOKEN BUDGET",
  "bridge.llmDailyOutputBudgetCopy": "Maximum model output for this classifier type each local day.",
  "bridge.llmDailyOutputUsage": "Today: {used} / {limit} output tokens used. Resets at local midnight.",
  "bridge.llmBatchSize": "CREATOR BATCH SIZE",
  "bridge.llmBatchSizeCopy": "How many eligible creators a manual batch processes. An activated model processes its current complete queue sequentially.",
  "bridge.llmMaximumTagCount": "MAXIMUM TAG COUNT",
  "bridge.llmMaximumTagCountCopy": "Maximum tags the model may return for one creator.",
  "bridge.llmLeafOnly": "Require leaf tags only",
  "bridge.llmLeafOnlyCopy": "On: parent tags are omitted from the LLM prompt. Off: the model may choose a generic parent tag, without expanding it into child tags.",
  "bridge.llmWebSearch": "Allow provider web search",
  "bridge.llmWebSearchCopy": "Available only when the selected model provider supports its own search tool.",
  "bridge.llmExternalTool": "Allow automatic platform data tool",
  "bridge.llmExternalToolCopy": "When available, uses the current {platform} API connection automatically. You cannot choose a tool connection here.",
  "bridge.llmUsePlatformAPIKey": "Use platform API key",
  "bridge.llmUsePlatformAPIKeyCopy": "Only if the saved {platform} creator URL is missing or its public page cannot provide a profile image, use the matching local API key as a fallback.",
  "bridge.humanTags": "Human tags",
  "bridge.llmTags": "LLM tags",
  "bridge.noTags": "No tags",
  "bridge.noDecision": "No decision",
  "bridge.notTag": "Not",
  "bridge.decisionPolicy": "Decision policy",
  "bridge.decisionPolicyCopy": "Every available human, LLM, and local-model signal contributes. First, second, and third priorities have relative weights of 3, 2, and 1.",
  "bridge.priorityFirst": "FIRST PRIORITY",
  "bridge.prioritySecond": "SECOND PRIORITY",
  "bridge.priorityThird": "THIRD PRIORITY",
  "bridge.source.human": "Human decision",
  "bridge.source.llmAssist": "LLM assist decision",
  "bridge.source.localModel": "Local model decision",
  "bridge.futureCopy": "This workspace remains available for the next Browser bridge experience. Connection controls live in Settings.",
  "bridge.macOnly": "MACOS LOCAL",
  "bridge.reserved": "Reserved workspace",
  "bridge.reservedCopy": "Browser bridge connection and server controls were moved to Settings. Keep this workspace for the next bridge workflow.",
  "bridge.settingsTitle": "Web-app bridge",
  "bridge.settingsCopy": "Run this app as the local hub or join a verified Mac Vault or Vault Classifier server.",
  "bridge.sharedHub": "Shared local Vault hub",
  "bridge.sharedHubCopy": "Mac Vault, Vault Classifier, and the Vault extension share one local address.",
  "bridge.hubAddress": "SERVER ADDRESS",
  "bridge.hubStatus": "CONNECTION STATUS",
  "bridge.peers": "CONNECTED APPS",
  "bridge.noPeers": "No other Vault apps connected",
  "bridge.connect": "Run or join local server",
  "bridge.disconnect": "Disconnect",
  "bridge.hostCopy": "When a joined host closes, this app first tries to host the shared local server itself.",
  "bridge.status.off": "Off",
  "bridge.status.connecting": "Connecting",
  "bridge.status.hosting": "Hosting local server",
  "bridge.status.joined-macapp": "Joined Mac Vault server",
  "bridge.status.joined-classifier": "Joined Vault Classifier server",
  "bridge.status.disconnected": "Starting local server",
  "bridge.status.error": "Server unavailable",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, compatible model, and optional named policy.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "ASSET BINDING",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.policy": "Named browser policies",
  "bridge.policyCopy": "Policies stay with the platform binding; the bridge can only request an existing local policy ID.",
  "bridge.configure": "Configure locally",
  "bridge.noPolicy": "No named policies are attached to the current bridge binding.",
  "data.title": "Classification data",
  "data.copy": "Add each public-content platform once, choose whether its rendered metadata is collected locally, and review entries by source.",
  "data.entries": "{count} COLLECTED ENTRIES",
  "data.addPlatform": "Add platform",
  "data.addPlatformCopy": "A platform owns one local tree and dataset binding. Collection starts on and sends only rendered public entries when this browser is connected.",
  "data.addPlatformAction": "Add platform",
  "data.allPlatformsAdded": "Every currently known public-content platform has been added.",
  "data.noPlatforms": "Add a platform to begin a local collection library.",
  "data.platform": "PLATFORM",
  "data.platformPanel": "PLATFORM COLLECTION",
  "data.deletePlatform": "Delete platform",
  "data.collectorAvailable": "Collector available",
  "data.collectorPlanned": "Collector not installed yet",
  "data.collecting": "COLLECTING",
  "data.collectionOff": "COLLECTION OFF",
  "data.collectToggle": "Collect rendered public entries on this platform",
  "data.applyCollection": "Apply collection setting",
  "data.classifierType": "CLASSIFIER TYPE",
  "data.classifierTypeCopy": "Selects the local decision configuration used by browser and manual classification",
  "data.noClassifierType": "No classifier type (legacy local engine)",
  "data.applyClassifierType": "Apply classifier type",
  "data.classifierTypeActive": "TYPE ACTIVE",
  "data.classifierTypeNone": "LEGACY ENGINE",
  "data.collectionDisabledCopy": "Collection is off. No entry title or source metadata is sent from the extension.",
  "data.waitingForEntries": "Collection is on. New rendered, non-ad entries will appear here by source.",
  "data.sourceCount": "{count} {sources}",
  "data.entryCount": "{count} ENTRIES",
  "data.discordLocalOnly": "Discord collects rendered messages from server channels you open in the browser, never direct messages. The collected content stays on this Mac and is never sent to a provider or remote service.",
  "data.unknownDate": "Unknown observation time",
  "data.diagnostics": "COLLECTION DIAGNOSTICS",
  "data.diagnosticsCopy": "Local pipeline checkpoints only. They never include page text, titles, creators, URLs, or entry IDs.",
  "data.clearDiagnostics": "Clear diagnostics",
  "data.noDiagnostics": "No collection checkpoints yet. Open a supported page to record the next attempt."
});
