window.VaultClassifierStrings = Object.freeze({
  "app.title": "Vault Classifier",
  "app.loading": "Loading the local Vault Classifier shell…",
  "hero.offline": "OFFLINE ON THIS MAC",
  "utility.close": "Close",
  "utility.settings.button": "Settings",
  "utility.settings.title": "Local settings",
  "utility.settings.copy": "Choose the resource limits and explicit local work this Mac is allowed to perform.",
  "language.label": "Language",
  "language.name.en": "English",
  "language.name.ar": "العربية",
  "language.name.bn": "বাংলা",
  "language.name.de": "Deutsch",
  "language.name.es": "Español",
  "language.name.fr": "Français",
  "language.name.hi": "हिन्दी",
  "language.name.id": "Bahasa Indonesia",
  "language.name.it": "Italiano",
  "language.name.ja": "日本語",
  "language.name.ko": "한국어",
  "language.name.nl": "Nederlands",
  "language.name.pa": "ਪੰਜਾਬੀ",
  "language.name.pl": "Polski",
  "language.name.pt": "Português",
  "language.name.ru": "Русский",
  "language.name.th": "ไทย",
  "language.name.tr": "Türkçe",
  "language.name.vi": "Tiếng Việt",
  "language.name.zh": "中文",
  "navigation.aria": "Classifier workspaces",
  "navigation.resize": "Resize classifier navigation",
  "navigation.title": "Classifier work",
  "navigation.subtitle": "Local development shell",
  "navigation.work": "Work",
  "navigation.control": "Control",
  "navigation.inspect": "Inspect entry",
  "navigation.inspectMeta": "Local decision",
  "navigation.policies": "Named policies",
  "navigation.policiesMeta": "Allow · dim · block",
  "navigation.activity": "Local activity",
  "navigation.activityMeta": "Cache and ledger",
  "navigation.training": "Local training",
  "navigation.trainingMeta": "Explicit labels",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "navigation.classifierTypes": "Classifier types",
  "navigation.apiKeys": "API keys",
  "navigation.apiKeysMeta": "Credential profiles & providers",
  "navigation.newType": "New type",
  "navigation.noTypes": "No classifier types yet. Create one for a platform.",
  "navigation.moveUp": "Move up",
  "navigation.moveDown": "Move down",
  "navigation.dragReorder": "Drag to reorder",
  "bridge.tabConfig": "Config",
  "bridge.tabTree": "Tag tree",
  "bridge.tabModel": "Local model",
  "settings.apiKeysTitle": "API keys & providers",
  "settings.apiKeysCopy": "Credential profiles for LLM assist and platform data.",
  "settings.manageApiKeys": "Manage API keys",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.profile.light": "Light",
  "enum.profile.balanced": "Balanced",
  "enum.profile.aggressive": "Aggressive",
  "enum.update.automatic": "Automatic",
  "enum.update.downloadThenAsk": "Ask first",
  "enum.update.manual": "Manual",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "inspect.title": "Inspect an entry",
  "inspect.copy": "Provide the same compact evidence a browser adapter will send. The classifier derives ancestors locally.",
  "inspect.feedDecision": "Feed decision",
  "inspect.pageDecision": "Page decision",
  "inspect.entryTitle": "Entry title",
  "inspect.required": "Required",
  "inspect.sourceID": "Source ID",
  "inspect.optional": "Optional",
  "inspect.platform": "Classification platform",
  "inspect.platformCopy": "Uses this platform's active classifier type",
  "inspect.surface": "Target surface",
  "inspect.surfaceHint": "Feed is +5% stricter",
  "inspect.classify": "Classify locally",
  "inspect.localOnly": "No upload · no provider key · local ledger",
  "inspect.classifyWithLLM": "Ask configured LLM",
  "inspect.llmClassifying": "Classifying…",
  "inspect.llmExplicitOnly": "Explicit manual request · sends this entry only to the attached provider · suggestion stays pending review",
  "inspect.noResult": "No local result yet. Classify an entry to inspect the decision and candidate tags.",
  "inspect.noLeaf": "No leaf met the current local threshold.",
  "inspect.noPolicy": "No active policy matched this entry.",
  "inspect.markFalseAllow": "Mark false allow",
  "inspect.markFalseDim": "Mark false dim",
  "inspect.markFalseBlock": "Mark false block",
  "inspect.policyDecision": "Policy decision",
  "inspect.threshold": "threshold {value}",
  "inspect.predictedLeaves": "Predicted leaves",
  "inspect.ancestorsComputed": "Ancestors are computed",
  "inspect.localScores": "Strongest local scores",
  "inspect.sourcePrior": "Direct + eligible source prior",
  "inspect.policyMatches": "Policy matches",
  "inspect.computedPath": "Computed path: {path}",
  "policies.title": "Named policies",
  "policies.copy": "Policies live in Vault Classifier. A browser can only ask for a policy ID and render the returned decision.",
  "policies.savedCount": "{count} SAVED",
  "policies.saved": "Saved policies",
  "policies.savedCopy": "Select a policy to edit its local criteria.",
  "policies.new": "New policy",
  "policies.empty": "No named policies are saved. Create one to classify against local criteria.",
  "policies.edit": "Edit policy",
  "policies.create": "Create a policy",
  "policies.editorCopy": "Exact tag IDs are validated locally before the policy is saved.",
  "policies.id": "Policy ID",
  "policies.idHint": "Letters, numbers, . _ -",
  "policies.displayName": "Display name",
  "policies.localOnly": "Local only",
  "policies.includeAny": "Include any tags",
  "policies.exactIDs": "Comma separated exact tag IDs",
  "policies.exclude": "Exclude tags",
  "policies.feedAction": "Feed action",
  "policies.feedHint": "Default is dim",
  "policies.pageAction": "Page action",
  "policies.pageHint": "Page dim becomes block",
  "policies.save": "Save locally",
  "common.delete": "Delete",
  "activity.title": "Local activity",
  "activity.copy": "The bounded cache and decision ledger stay on this Mac. Viewing content is never a training label.",
  "activity.localOnly": "LOCAL ONLY",
  "activity.cache": "Cache",
  "activity.ledger": "Ledger",
  "activity.corrections": "Corrections",
  "activity.resources": "Resource controls",
  "activity.resourcesCopy": "Preferences only: this development build has no endpoint or automatic task.",
  "activity.profile": "Resource profile",
  "activity.profileHint": "Local capacity default",
  "activity.cacheCapacity": "Cache capacity",
  "activity.uniqueEntries": "Unique entries",
  "activity.packageUpdates": "Package updates",
  "activity.preference": "Local preference",
  "activity.idleWork": "Allow low-priority cache refresh work",
  "activity.backgroundSync": "Allow daily package checks when an endpoint is configured",
  "activity.save": "Save local resource settings",
  "activity.recent": "Recent decisions",
  "activity.newest": "Newest first.",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "activity.empty": "No local decisions yet. Inspect an entry to create the first ledger record.",
  "training.title": "Local training",
  "training.copy": "Rebuild a bounded correction layer only from labels you explicitly store. Views, clicks, raw corrections, and provider output alone are never labels.",
  "training.localOnly": "LOCAL ONLY",
  "training.noLabels": "NO LABELS",
  "training.labels": "Explicit labels",
  "training.features": "Model features",
  "training.lastRebuild": "Last rebuild",
  "training.notYet": "Not yet",
  "training.labelCount": "{count} labels",
  "training.currentLabel": "Current entry label",
  "training.currentLabelCopy": "Classify an entry first, then explicitly describe predictable leaf tags. Parent nodes are computed locally.",
  "training.positive": "Positive leaf tags",
  "training.negative": "Negative leaf tags",
  "training.commaSeparated": "Comma separated",
  "training.optionalCommaSeparated": "Optional, comma separated",
  "training.store": "Store current label",
  "training.replace": "A new label for the same source entry replaces its prior local label.",
  "training.rebuild": "Rebuild correction layer",
  "training.rebuildCopy": "This deterministic local run affects new classifications only.",
  "training.passes": "Passes",
  "training.passesHint": "1–12",
  "training.localAction": "Local action",
  "training.retrain": "Retrain local model",
  "training.lastRun": "Last rebuild: {labels} labels · {updates} updates · {epochs} passes · taxonomy {taxonomy}",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this Mac's package, explicit training corpus, policies, and correction layer. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in this Mac's Keychain. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "Owner code",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current model snapshot plus three previous snapshots. Browsing cache and decision ledger are excluded.",
  "backup.localFolder": "Local folder",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after every successful local model rebuild",
  "backup.save": "Save backup mode",
  "backup.create": "Create backup now",
  "integration.title": "Browser bridge",
  "integration.copy": "The Chrome and Edge adapter requires registered Native Messaging authentication.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Local authentication",
  "integration.keychain": "Keychain-backed proof",
  "integration.host": "Native host",
  "integration.notRegistered": "Requires installer registration",
  "integration.server": "Protocol",
  "integration.notRequired": "Version 4",
  "integration.notice": "A signed installer must supply confirmed stable extension IDs and the host path. Until then, Chrome and Edge stay disconnected rather than using an unauthenticated bridge.",
  "navigation.tagTree": "Tag tree",
  "navigation.tagTreeMeta": "Shared tree library",
  "navigation.localModel": "Local model",
  "navigation.localModelMeta": "Train and recover",
  "navigation.llmAssist": "LLM assist",
  "navigation.llmAssistMeta": "Credential profiles",
  "navigation.browserBridge": "Classifier Type",
  "navigation.browserBridgeMeta": "Decision brains",
  "navigation.classificationData": "Classification data",
  "navigation.classificationDataMeta": "Manual and LLM records",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.title": "Tag tree",
  "tree.copy": "Create and evolve reusable local tag trees. Every edit publishes a revision before a compatible model can train.",
  "tree.sharedLibrary": "Shared library",
  "tree.active": "Active tree",
  "tree.activeCopy": "Current local revision {revision}",
  "tree.inspector": "Node inspector",
  "tree.inspectorCopy": "Changes publish a new tree revision and make the previous model incompatible until retraining finishes.",
  "tree.activeNode": "ACTIVE",
  "tree.nodeName": "Node name",
  "tree.level": "Level {value}",
  "tree.rootNode": "Root node",
  "tree.childOf": "Child of {name}",
  "tree.nodeCount": "{count} nodes",
  "tree.panel": "Tree panel",
  "tree.multiplePanels": "Each tree keeps its own editing panel.",
  "tree.contextHint": "Click or right-click to edit this node",
  "tree.saveNode": "Save node",
  "tree.createNode": "Create node",
  "tree.editNode": "Edit node",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a node to make it the parent.",
  "tree.connection": "Connection",
  "tree.disconnection": "Disconnection",
  "tree.deleteNode": "Delete node",
  "tree.rename": "Rename",
  "tree.renameTree": "Rename tree",
  "tree.saveTreeName": "Save tree",
  "tree.rearrange": "Rearrange",
  "tree.delete": "Delete",
  "tree.confirmDelete": "Delete tree?",
  "tree.confirmDeleteCopy": "This permanently removes the tree, its dependent local models, and any platform link to it.",
  "tree.confirmDeleteAction": "Delete tree",
  "tree.canvasHint": "Right-click empty space to create a root node. Click or right-click a node to edit it. Drag a node to reposition its branch.",
  "tree.empty": "No nodes are in this local tree yet.",
  "tree.addTag": "Add a tag",
  "tree.addCopy": "Tags stay local. Adding a node creates a new tree revision.",
  "tree.tagName": "Tag name",
  "tree.tagDescription": "Tag description",
  "tree.tagDescriptionCopy": "Optional local context sent with this eligible tag in LLM classification requests.",
  "tree.add": "Add local tag",
  "tree.newTree": "New tag tree",
  "tree.newCopy": "A new tree is a reusable library asset. Bind it deliberately to a browser platform.",
  "tree.treeName": "Tree name",
  "tree.create": "Create tree",
  "model.title": "Local model",
  "model.copy": "Build a local neural classifier bound to a classifier type. It trains incrementally on that type's approved creator decisions.",
  "model.sharedLibrary": "Shared library",
  "model.multiplePanels": "A classifier type owns at most one local model.",
  "model.forClassifierType": "Classifier type",
  "model.noEligibleTypes": "Every eligible classifier type already has a local model.",
  "model.newModel": "New local model",
  "model.modelName": "Model name",
  "model.create": "Create model",
  "model.panel": "Model panel",
  "model.version": "Version {value}",
  "model.rename": "Rename model",
  "model.delete": "Delete model",
  "model.confirmDelete": "Delete this local model?",
  "model.confirmDeleteCopy": "This removes its stored neural artifact and cannot be undone.",
  "model.setup": "Model setup",
  "model.setupCopy": "A model inherits its tree, dataset, and platform from its classifier type and trains on the native on-device embedding.",
  "model.boundTree": "Tree",
  "model.boundPlatform": "Platform",
  "model.baseLanguageModel": "Base language model",
  "model.baseCopy": "The local model uses the native on-device embedding. Downloadable base models are not available in this build.",
  "model.base.none": "Native on-device embedding",
  "model.base.allMiniLML6V2": "all-MiniLM-L6-v2",
  "model.base.allMPNetBaseV2": "all-mpnet-base-v2",
  "model.base.multilingualE5Small": "multilingual-e5-small",
  "model.base.multilingualE5Base": "multilingual-e5-base",
  "model.base.multilingualE5Large": "multilingual-e5-large",
  "model.base.bgeM3": "bge-m3",
  "model.trainingScope": "{incorporated} decisions folded in · {pending} new to fold",
  "model.train": "Train local model",
  "model.trainMore": "Fold new decisions",
  "model.trainedRun": "Folded {folded} new decisions · {total} total · {examples} examples this pass",
  "model.untrained": "Not trained yet. Run a pass to fold in this type's approved creator decisions.",
  "model.empty": "No local models yet. Create one for a classifier type to train on its approved creator decisions.",
  "model.ready": "READY",
  "model.needsTraining": "NEEDS TRAINING",
  "model.updatesPending": "UPDATES PENDING",
  "model.models": "Models",
  "model.labels": "Approved labels",
  "model.versions": "Version",
  "model.active": "Active compatible model",
  "model.activeCopy": "A platform may activate one model whose tree and dataset revisions exactly match.",
  "model.none": "No local model",
  "model.boundRevisions": "Tree r{tree} · Data r{data}",
  "model.boundType": "Bound to {type}",
  "model.localTraining": "Explicit local training",
  "model.trainingCopy": "Training is user-controlled local work. Browsing-time inference remains fast and local.",
  "model.passes": "Training passes",
  "model.explicitAction": "Local action",
  "model.backup": "Advanced backup",
  "model.backupCopy": "Optional local snapshots are owner-code gated and never leave this Mac.",
  "model.advanced": "Backup settings",
  "model.backupStatus": "Latest plus {count} previous snapshots",
  "llm.title": "LLM assist",
  "llm.copy": "Create local language-model, blockable-platform data, or raw web-search profiles. An activated classifier type processes eligible collected creators one at a time.",
  "llm.keyLibrary": "Key library",
  "llm.providerType": "Provider type",
  "llm.chooseProviderType": "Choose a provider type",
  "llm.createKey": "Create key",
  "llm.createCopy": "Use a direct model preset, an official platform-data API, Serper or You.com Search, or a compatible custom model endpoint.",
  "llm.empty": "No API-key profiles yet. Choose a provider type, then create its local setup panel.",
  "llm.providerPanel": "Provider panel",
  "llm.provider.openAI": "OpenAI",
  "llm.provider.openAICompatible": "OpenAI-compatible API",
  "llm.provider.deepSeek": "DeepSeek",
  "llm.provider.gemini": "Gemini",
  "llm.provider.anthropic": "Anthropic",
  "llm.provider.mistral": "Mistral AI",
  "llm.provider.cohere": "Cohere",
  "llm.provider.groq": "Groq",
  "llm.provider.openRouter": "OpenRouter",
  "llm.provider.ollama": "Ollama",
  "llm.provider.youtubeData": "YouTube Data API",
  "llm.provider.twitch": "Twitch",
  "llm.provider.reddit": "Reddit",
  "llm.provider.xPlatform": "X API",
  "llm.provider.tikTok": "TikTok",
  "llm.provider.instagramGraph": "Instagram Graph API",
  "llm.provider.facebookGraph": "Facebook Graph API",
  "llm.provider.serper": "Serper",
  "llm.provider.youSearch": "You.com Search",
  "llm.provider.custom": "Custom API",
  "llm.providerGroup.models": "Language models",
  "llm.providerGroup.platform": "BLOCKABLE PLATFORM DATA APIs",
  "llm.providerGroup.search": "WEB SEARCH APIs",
  "llm.providerGroup.custom": "CUSTOM AND COMPATIBLE APIs",
  "llm.deleteProfile": "Delete profile",
  "llm.apiKeyOrToken": "API key or token",
  "llm.apiEndpoint": "API endpoint",
  "llm.testModel": "Model for test",
  "llm.test": "Test request",
  "llm.testing": "Testing…",
  "llm.testSucceeded": "Test request succeeded. The provider is ready.",
  "llm.tokenUsage": "Token usage",
  "llm.tokenTotal": "{total} aggregate tokens",
  "llm.apiCalls": "API calls",
  "llm.responseShape": "Last unparseable response shape",
  "llm.protocol.accountID": "Account ID",
  "llm.protocol.apiVersion": "API version",
  "llm.protocol.clientID": "Client ID",
  "llm.protocol.location": "Location",
  "llm.protocol.projectID": "Project ID",
  "llm.protocol.region": "Region",
  "llm.protocol.userAgent": "User agent",
  "llm.protocol.searchEngineID": "Search engine ID",
  "llm.protocol.protocolFamily": "Request family",
  "bridge.title": "Classifier Type",
  "bridge.copy": "Build local decision brains from matching trees, data, models, and explicit LLM assist profiles. Browser connection controls live in Settings.",
  "bridge.typeLibrary": "Decision brain library",
  "bridge.typePanel": "Classifier type",
  "bridge.newTypeName": "New classifier type",
  "bridge.newTypeNameCopy": "For example, YouTube creator focus",
  "bridge.createType": "Create type",
  "bridge.emptyTypes": "Create a classifier type to assemble a local decision brain.",
  "bridge.selectType": "Select a classifier type on the left, or click + New type.",
  "bridge.typeName": "Type name",
  "bridge.saveType": "Save type",
  "bridge.deleteType": "Delete type",
  "bridge.typeMatchCopy": "Tag tree: {tree} · Local data: {data}",
  "bridge.missingAsset": "Missing asset",
  "bridge.configured": "CONFIGURED",
  "bridge.needsSource": "NEEDS SOURCE",
  "bridge.assetSelectionCopy": "Choose one platform. Its platform binding supplies this type's tag tree and collected classification data.",
  "bridge.applicablePlatform": "Applicable platform",
  "bridge.platformData": "Platform data",
  "bridge.applicablePlatformCopy": "Only one platform can be used by a classifier type.",
  "bridge.applicablePlatformLocked": "Locked · {count} approved decisions are bound to this platform. Create a new classifier type to use a different one.",
  "bridge.platformLockedNote": "Locked to this platform. It can't be changed for this classifier type.",
  "bridge.lockPlatformTitle": "Lock this classifier type to its platform?",
  "bridge.lockPlatformCopy": "Tagging a source binds decisions to {platform}. After this you can't change the applicable platform for this classifier type. Create a new type to use a different platform.",
  "bridge.lockPlatformConfirm": "Lock and continue",
  "common.cancel": "Cancel",
  "trash.confirmTitle": "Delete this — are you sure?",
  "trash.confirmCopy": "This moves “{name}” and all of its data to the trash. It is recoverable for 24 hours, then permanently purged.",
  "trash.typeNameLabel": "Type the name to confirm",
  "trash.confirmDelete": "Delete",
  "trash.deleted": "DELETED · restorable for 24h",
  "trash.title": "Trash",
  "trash.restore": "Restore entry",
  "trash.permanentlyDelete": "Permanently delete",
  "bridge.noApplicablePlatform": "Choose a platform",
  "bridge.platformDataChoose": "Choose a platform to bind its local classification data.",
  "bridge.platformDataAutoCreate": "adds local data",
  "bridge.platformDataWillCreate": "Local classification data for {platform} will be added when you save this type.",
  "bridge.platformDataBound": "Official API evidence connection: {profile}",
  "bridge.platformDataMissingKey": "No local {platform} official API credential is configured. Configure web search to classify with collected evidence.",
  "bridge.platformDataUnavailable": "{platform} has no official API evidence adapter. Configure web search before LLM creator classification.",
  "bridge.platformDataSearchReady": "Web search is ready; the model may classify without official platform evidence.",
  "bridge.manualOnly": "Manual only",
  "bridge.manualOnlyCopy": "Twitch, Reddit, and Discord keep normal manual collection and tagging, but Local model and LLM Assist are unavailable for this classifier type.",
  "bridge.localModel": "Local model",
  "bridge.localModelCopy": "This type's local model trains on its approved creator decisions. Manage it in the Local model section.",
  "bridge.localModelBound": "Model · {name}",
  "bridge.localModelOpen": "Open Local model",
  "bridge.localModelNone": "No local model yet for this type.",
  "bridge.localModelCreate": "Create in Local model",
  "bridge.noLocalModel": "No local model",
  "bridge.sourceKind.creator": "creator",
  "bridge.sourceKind.creatorPlural": "creators",
  "bridge.sourceKind.account": "account",
  "bridge.sourceKind.accountPlural": "accounts",
  "bridge.sourceKind.subreddit": "subreddit",
  "bridge.sourceKind.subredditPlural": "subreddits",
  "bridge.sourceKind.server": "Discord server",
  "bridge.sourceKind.serverPlural": "Discord servers",
  "bridge.manualSource": "Manual {source} classification",
  "bridge.manualSourceCopy": "Choose one active leaf tag and record an independent tagged or not-tagged decision for this {source}. A decision for one tag never decides another tag.",
  "bridge.sourceCount": "{count} {sources}",
  "bridge.sourceTagEmpty": "No {sources} in this section yet.",
  "bridge.sourceDecisionList": "{source} decisions",
  "bridge.sourceDecisionListCopy": "Human and LLM tags are shown together for every collected {sources}.",
  "bridge.noSources": "Collect public entries first. Their {sources} will appear here for manual classification.",
  "bridge.creatorTagNavigation": "Active leaf tags",
  "bridge.creatorTagNeedDecision": "Need decision",
  "bridge.creatorTagTagged": "Tagged as {tag}",
  "bridge.creatorTagNotTagged": "Not tagged as {tag}",
  "bridge.creatorTagTag": "Tag as {tag}",
  "bridge.creatorTagMarkNot": "Not {tag}",
  "bridge.creatorTagClear": "Clear {tag}",
  "bridge.creatorSubscribers": "{count} subscribers",
  "bridge.creatorTags": "Active leaf tags",
  "bridge.creatorTagsCopy": "Choose one or more tags",
  "bridge.classifyCreator": "Save creator classification",
  "bridge.noCreatorTags": "Add active leaf tags to the selected tag tree before classifying creators.",
  "bridge.llmAssist": "LLM assist",
  "bridge.llmAssistCopy": "Select exactly one provider connection and one model. The app supplies bounded official evidence when available; an explicit search mode can let the same model search only when it is unsure.",
  "bridge.llmAdvanced": "LLM advanced settings",
  "bridge.llmAdvancedCopy": "Token budgets, pacing, evidence, tag limits, and web search. Sensible defaults apply if you leave these.",
  "bridge.llmActivate": "Activate",
  "bridge.llmDeactivate": "Deactivate",
  "bridge.llmActive": "ACTIVE · New complete creators are classified sequentially.",
  "bridge.llmInactive": "INACTIVE · Save a model, then activate it to begin classification.",
  "bridge.llmActivationRunning": "ACTIVE · Classifying creators sequentially…",
  "bridge.llmModelRequired": "MODEL REQUIRED · Choose a fetched model before classification can be enabled.",
  "bridge.llmClassificationStatus": "Classification status",
  "bridge.llmQueuedCreators": "{count} eligible creators waiting",
  "bridge.llmCompletedToday": "{count} completed today",
  "bridge.llmLastResult": "Last request: {result}",
  "bridge.llmOutcomeSucceeded": "succeeded",
  "bridge.llmOutcomeFailed": "failed",
  "bridge.noLLMProfiles": "Create an LLM Assist profile before attaching it here.",
  "bridge.noLLMModel": "No LLM model",
  "bridge.llmProvider": "Local provider connection",
  "bridge.llmProviderCopy": "The API key stays on this Mac. It grants no model, platform, or decision policy by itself.",
  "bridge.llmModel": "Model identifier",
  "bridge.llmModelCopy": "Exactly one fetched model is active for this classifier type.",
  "bridge.llmChooseProviderFirst": "Choose a provider connection before selecting its model.",
  "bridge.llmChooseModel": "Choose a fetched model",
  "bridge.llmProbeModels": "Probe",
  "bridge.llmProbingModels": "Probing models…",
  "bridge.llmProbeModelsCopy": "Probe this provider to load its models. The list stays cached until the next successful Probe.",
  "bridge.llmDailyTokenBudget": "Daily token budget",
  "bridge.llmDailyTokenBudgetCopy": "Maximum aggregate model input, output, reasoning, and tool tokens for this classifier type each local day.",
  "bridge.llmDailyTokenUsage": "Today: {used} / {limit} aggregate tokens used. Resets at local midnight.",
  "bridge.llmMaximumTokens": "Max tokens",
  "bridge.llmMaximumTokensCopy": "Maximum output tokens for one request. The remaining daily budget can lower it.",
  "bridge.llmExtraDirection": "Extra direction",
  "bridge.llmExtraDirectionCopy": "Optional local instructions appended before the required label JSON response.",
  "bridge.llmClassificationPace": "Classification pace",
  "bridge.llmClassificationPaceCopy": "Upper bound on batches (requests) started per minute (1–120), not a guaranteed rate. Each batch is one request whose next batch never starts before the current one finishes, so provider latency can make the real rate lower than pace × batch size.",
  "bridge.llmBatchSize": "Creator batch size",
  "bridge.llmBatchSizeCopy": "How many eligible creators go into one classification request. An activated run sends the whole batch to the model in a single call — every creator is a numbered target in the same prompt — once per classification-pace interval.",
  "bridge.llmOfficialContentEvidenceCount": "Official content records",
  "bridge.llmOfficialContentEvidenceCountCopy": "Recent public content records requested from the applicable official platform API (1–50). Platforms may return fewer; configured search can fill evidence gaps. Records are used only for that prompt.",
  "bridge.llmMaximumTagCount": "Maximum tag count",
  "bridge.llmMaximumTagCountCopy": "Maximum tags the model may return for one creator.",
  "bridge.llmLeafOnly": "Require leaf tags only",
  "bridge.llmLeafOnlyCopy": "On: parent tags are omitted from the LLM prompt. Off: the model may choose a generic parent tag, without expanding it into child tags.",
  "bridge.llmWebSearchMode": "Web search mode",
  "bridge.llmWebSearchModeCopy": "Choose no search, the model provider's hosted search, or one external search connection the same model may call when unsure.",
  "bridge.llmWebSearchOff": "Off",
  "bridge.llmWebSearchNative": "Model provider search",
  "bridge.llmWebSearchAttached": "Attached search API",
  "bridge.llmNativeWebSearchCopy": "This model receives its native hosted-search tool and is told to search only when the supplied evidence is insufficient. If this provider cannot combine search with an output schema, a malformed answer gets one charged same-model schema repair without repeating search.",
  "bridge.llmAttachedWebSearchCopy": "The same classifier model decides whether to call web_search. Its model-generated query is sent through this Serper or You.com connection; the app returns one bounded result set to that conversation, then requires final label JSON. If tools cannot coexist with an output schema, a malformed answer gets one charged same-model schema repair without repeating search.",
  "bridge.llmEvidenceRequired": "LLM creator classification requires a ready official platform API connection or a ready web search mode.",
  "bridge.llmWebSearchProvider": "Web search connection",
  "bridge.llmWebSearchProviderCopy": "Choose the independent Serper or You.com Search connection exposed as the model's web_search function.",
  "bridge.llmChooseSearchProvider": "Choose a web search connection",
  "bridge.humanTags": "Human tags",
  "bridge.llmTags": "LLM tags",
  "bridge.noTags": "No tags",
  "bridge.noDecision": "No decision",
  "bridge.notTag": "Not",
  "bridge.searchSources": "Search by name…",
  "bridge.searchCount": "{shown} of {total}",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, compatible model, and optional named policy.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "Asset binding",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.policy": "Named browser policies",
  "bridge.policyCopy": "Policies stay with the platform binding; the bridge can only request an existing local policy ID.",
  "bridge.configure": "Configure locally",
  "bridge.noPolicy": "No named policies are attached to the current bridge binding.",
  "data.title": "Classification data",
  "data.copy": "Add each public-content platform once, choose whether its rendered metadata is collected locally, and review entries by source.",
  "data.entries": "{count} COLLECTED ENTRIES",
  "data.addPlatform": "Add platform",
  "data.addPlatformCopy": "A platform owns one local tree and dataset binding. Collection starts on and sends only rendered public entries when this browser is connected.",
  "data.addPlatformAction": "Add platform",
  "data.allPlatformsAdded": "Every currently known public-content platform has been added.",
  "data.noPlatforms": "Add a platform to begin a local collection library.",
  "data.platform": "Platform",
  "data.platformPanel": "Platform collection",
  "data.deletePlatform": "Delete platform",
  "data.collectorAvailable": "Collector available",
  "data.collectorPlanned": "Collector not installed yet",
  "data.collecting": "COLLECTING",
  "data.collectionOff": "COLLECTION OFF",
  "data.collectToggle": "Collect rendered public entries on this platform",
  "data.applyCollection": "Apply collection setting",
  "data.classifierType": "Classifier type",
  "data.classifierTypeCopy": "Selects the local decision configuration used by browser and manual classification",
  "data.noClassifierType": "No classifier type (legacy local engine)",
  "data.applyClassifierType": "Apply classifier type",
  "data.classifierTypeActive": "TYPE ACTIVE",
  "data.classifierTypeNone": "LEGACY ENGINE",
  "data.collectionDisabledCopy": "Collection is off. No entry title or source metadata is sent from the extension.",
  "data.waitingForEntries": "Collection is on. New rendered, non-ad entries will appear here by source.",
  "data.sourceCount": "{count} {sources}",
  "data.entryCount": "{count} entries",
  "data.discordLocalOnly": "Discord collects rendered messages from server channels you open in the browser, never direct messages. The collected content stays on this Mac and is never sent to a provider or remote service.",
  "data.unknownDate": "Unknown observation time",
  "data.diagnostics": "Collection diagnostics",
  "data.diagnosticsCopy": "Local pipeline checkpoints only. They never include page text, titles, creators, URLs, or entry IDs.",
  "data.clearDiagnostics": "Clear diagnostics",
  "data.noDiagnostics": "No collection checkpoints yet. Open a supported page to record the next attempt."
});
