window.VaultClassifierStrings = Object.freeze({
  "app.title": "Vault Classifier",
  "app.loading": "Loading the local Vault Classifier shell…",
  "hero.offline": "OFFLINE ON THIS MAC",
  "navigation.aria": "Classifier workspaces",
  "navigation.title": "Classifier work",
  "navigation.subtitle": "Local development shell",
  "navigation.work": "WORK",
  "navigation.control": "CONTROL",
  "navigation.inspect": "Inspect entry",
  "navigation.inspectMeta": "Local decision",
  "navigation.policies": "Named policies",
  "navigation.policiesMeta": "Allow · dim · block",
  "navigation.activity": "Local activity",
  "navigation.activityMeta": "Cache and ledger",
  "navigation.training": "Local training",
  "navigation.trainingMeta": "Explicit labels",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.audit": "Personal audit",
  "navigation.auditMeta": "Optional Gemini review",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.profile.light": "Light",
  "enum.profile.balanced": "Balanced",
  "enum.profile.aggressive": "Aggressive",
  "enum.update.automatic": "Automatic",
  "enum.update.downloadThenAsk": "Ask first",
  "enum.update.manual": "Manual",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "inspect.title": "Inspect an entry",
  "inspect.copy": "Provide the same compact evidence a browser adapter will send. The classifier derives ancestors locally.",
  "inspect.feedDecision": "FEED DECISION",
  "inspect.pageDecision": "PAGE DECISION",
  "inspect.entryTitle": "ENTRY TITLE",
  "inspect.required": "Required",
  "inspect.sourceID": "SOURCE ID",
  "inspect.optional": "Optional",
  "inspect.surface": "TARGET SURFACE",
  "inspect.surfaceHint": "Feed is +5% stricter",
  "inspect.classify": "Classify locally",
  "inspect.localOnly": "No upload · no provider key · local ledger",
  "inspect.noResult": "No local result yet. Classify an entry to inspect the decision and candidate tags.",
  "inspect.noLeaf": "No leaf met the current local threshold.",
  "inspect.noPolicy": "No active policy matched this entry.",
  "inspect.markFalseAllow": "Mark false allow",
  "inspect.markFalseDim": "Mark false dim",
  "inspect.markFalseBlock": "Mark false block",
  "inspect.policyDecision": "POLICY DECISION",
  "inspect.threshold": "threshold {value}",
  "inspect.predictedLeaves": "PREDICTED LEAVES",
  "inspect.ancestorsComputed": "Ancestors are computed",
  "inspect.localScores": "STRONGEST LOCAL SCORES",
  "inspect.sourcePrior": "Direct + eligible source prior",
  "inspect.policyMatches": "POLICY MATCHES",
  "inspect.computedPath": "Computed path: {path}",
  "policies.title": "Named policies",
  "policies.copy": "Policies live in Vault Classifier. A browser can only ask for a policy ID and render the returned decision.",
  "policies.savedCount": "{count} SAVED",
  "policies.saved": "Saved policies",
  "policies.savedCopy": "Select a policy to edit its local criteria.",
  "policies.new": "New policy",
  "policies.empty": "No named policies are saved. Create one to classify against local criteria.",
  "policies.edit": "Edit policy",
  "policies.create": "Create a policy",
  "policies.editorCopy": "Exact tag IDs are validated locally before the policy is saved.",
  "policies.id": "POLICY ID",
  "policies.idHint": "Letters, numbers, . _ -",
  "policies.displayName": "DISPLAY NAME",
  "policies.localOnly": "Local only",
  "policies.includeAny": "INCLUDE ANY TAGS",
  "policies.exactIDs": "Comma separated exact tag IDs",
  "policies.exclude": "EXCLUDE TAGS",
  "policies.feedAction": "FEED ACTION",
  "policies.feedHint": "Default is dim",
  "policies.pageAction": "PAGE ACTION",
  "policies.pageHint": "Page dim becomes block",
  "policies.save": "Save locally",
  "common.delete": "Delete",
  "activity.title": "Local activity",
  "activity.copy": "The bounded cache and decision ledger stay on this Mac. Viewing content is never a training label.",
  "activity.localOnly": "LOCAL ONLY",
  "activity.cache": "CACHE",
  "activity.ledger": "LEDGER",
  "activity.corrections": "CORRECTIONS",
  "activity.resources": "Resource controls",
  "activity.resourcesCopy": "Preferences only: this development build has no endpoint or automatic task.",
  "activity.profile": "RESOURCE PROFILE",
  "activity.profileHint": "Local capacity default",
  "activity.cacheCapacity": "CACHE CAPACITY",
  "activity.uniqueEntries": "Unique entries",
  "activity.packageUpdates": "PACKAGE UPDATES",
  "activity.preference": "Local preference",
  "activity.idleWork": "Allow low-priority cache refresh work",
  "activity.backgroundSync": "Allow daily package checks when an endpoint is configured",
  "activity.auditDispatch": "Allow personal LLM audit dispatch",
  "activity.save": "Save local resource settings",
  "activity.recent": "Recent decisions",
  "activity.newest": "Newest first.",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "activity.empty": "No local decisions yet. Inspect an entry to create the first ledger record.",
  "training.title": "Local training",
  "training.copy": "Rebuild a bounded correction layer only from labels you explicitly store. Views, clicks, raw corrections, and provider output alone are never labels.",
  "training.localOnly": "LOCAL ONLY",
  "training.noLabels": "NO LABELS",
  "training.labels": "EXPLICIT LABELS",
  "training.features": "MODEL FEATURES",
  "training.lastRebuild": "LAST REBUILD",
  "training.notYet": "Not yet",
  "training.labelCount": "{count} labels",
  "training.currentLabel": "Current entry label",
  "training.currentLabelCopy": "Classify an entry first, then explicitly describe predictable leaf tags. Parent nodes are computed locally.",
  "training.positive": "POSITIVE LEAF TAGS",
  "training.negative": "NEGATIVE LEAF TAGS",
  "training.commaSeparated": "Comma separated",
  "training.optionalCommaSeparated": "Optional, comma separated",
  "training.store": "Store current label",
  "training.replace": "A new label for the same source entry replaces its prior local label.",
  "training.rebuild": "Rebuild correction layer",
  "training.rebuildCopy": "This deterministic local run affects new classifications only.",
  "training.passes": "PASSES",
  "training.passesHint": "1–12",
  "training.localAction": "LOCAL ACTION",
  "training.retrain": "Retrain local model",
  "training.lastRun": "Last rebuild: {labels} labels · {updates} updates · {epochs} passes · taxonomy {taxonomy}",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this Mac's package, explicit training corpus, policies, and correction layer. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in this Mac's Keychain. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "OWNER CODE",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current model snapshot plus three previous snapshots. Browsing cache, decision ledger, and audit history are excluded.",
  "backup.localFolder": "LOCAL FOLDER",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after every successful local model rebuild",
  "backup.save": "Save backup mode",
  "backup.create": "Create backup now",
  "audit.title": "Personal audit",
  "audit.copy": "Optional review of potential false allows. A provider call happens only after an explicit button press and a conservative local token reservation.",
  "audit.resourceHold": "RESOURCE HOLD",
  "audit.keyNeeded": "KEY NEEDED",
  "audit.ready": "READY",
  "audit.settings": "Local audit settings",
  "audit.settingsCopy": "The only fixed adapter in this development slice is Gemini. No arbitrary endpoint can be entered here.",
  "audit.enable": "Enable personal local auditing",
  "audit.provider": "APPROVED PROVIDER",
  "audit.fixedAdapter": "Fixed adapter",
  "audit.gemini": "Gemini",
  "audit.reasoning": "REASONING",
  "audit.perRequest": "Per request",
  "audit.model": "MODEL IDENTIFIER",
  "audit.modelHint": "Validated before any request",
  "audit.selection": "SELECTION",
  "audit.selectionHint": "Local only",
  "audit.outputCap": "MAX OUTPUT TOKENS",
  "audit.outputHint": "2,048 max",
  "audit.requestCap": "PER REQUEST",
  "audit.reservation": "Local reservation",
  "audit.weekly": "WEEKLY",
  "audit.accounting": "Local accounting",
  "audit.monthly": "MONTHLY",
  "audit.polish": "Use confirmed audit labels only to polish this Mac's personal model",
  "audit.save": "Save local audit settings",
  "audit.dispatchHeld": "Resource controls currently prevent Gemini dispatch. Enable Personal LLM audit dispatch in Local activity before a queued item can spend tokens.",
  "audit.key": "Gemini API key",
  "audit.keyCopy": "Keychain only. The extension, native host, local state file, diagnostics, and server never receive this credential.",
  "audit.keychain": "KEYCHAIN CREDENTIAL",
  "audit.replaceHint": "Enter a replacement",
  "audit.keyHint": "Paste a Gemini API key",
  "audit.replace": "Replace",
  "audit.store": "Store",
  "audit.remove": "Remove",
  "audit.queueRisk": "Queue risk-selected allows",
  "audit.queueCurrent": "Queue current entry for review",
  "audit.copyDiagnostics": "Copy redacted diagnostics",
  "audit.queued": "QUEUED",
  "audit.settled": "SETTLED",
  "audit.inFlight": "IN FLIGHT",
  "audit.uncertain": "UNCERTAIN",
  "audit.weeklyTokens": "WEEKLY TOKENS",
  "audit.monthlyTokens": "MONTHLY TOKENS",
  "audit.queue": "Local audit queue",
  "audit.queueCopy": "No evidence leaves this Mac until you explicitly run a configured adapter.",
  "audit.risk": "Risk {value}",
  "audit.eligible": "ELIGIBLE",
  "audit.held": "HELD",
  "audit.running": "Running…",
  "audit.run": "Run Gemini",
  "audit.emptyQueue": "No local audit candidates are queued.",
  "audit.results": "Local audit results",
  "audit.resultsCopy": "Provider output is only a local review suggestion and never trains automatically.",
  "audit.noLeaf": "No returned leaf tags",
  "audit.tokens": "{count} tokens",
  "audit.confirm": "I confirm this false allow:",
  "audit.polishPolicy": "Polish {policy}",
  "audit.emptyResults": "No local audit results yet.",
  "integration.title": "Browser bridge",
  "integration.copy": "The source-only Chrome and Edge adapter remains deliberately unregistered and disabled.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Pairing secret",
  "integration.keychain": "Keychain",
  "integration.host": "Native host",
  "integration.notRegistered": "Not registered",
  "integration.server": "Server",
  "integration.notRequired": "Not required",
  "integration.notice": "A signed installer must later supply stable extension IDs and the host path. Until then, Chrome and Edge fail open rather than applying a rule.",
  "navigation.tagTree": "Tag tree",
  "navigation.tagTreeMeta": "Shared tree library",
  "navigation.localModel": "Local model",
  "navigation.localModelMeta": "Train and recover",
  "navigation.llmAssist": "LLM assist",
  "navigation.llmAssistMeta": "Explicit provider runs",
  "navigation.browserBridge": "Browser bridge",
  "navigation.browserBridgeMeta": "Chrome · Edge · YouTube",
  "navigation.classificationData": "Classification data",
  "navigation.classificationDataMeta": "Manual and LLM records",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.title": "Tag tree",
  "tree.copy": "Create and evolve reusable local tag trees. Every edit publishes a revision before a compatible model can train.",
  "tree.sharedLibrary": "SHARED LIBRARY",
  "tree.active": "Active tree",
  "tree.activeCopy": "Current local revision {revision}",
  "tree.inspector": "NODE INSPECTOR",
  "tree.inspectorCopy": "Changes publish a new tree revision and make the previous model incompatible until retraining finishes.",
  "tree.activeNode": "ACTIVE",
  "tree.nodeName": "NODE NAME",
  "tree.level": "Level {value}",
  "tree.rootNode": "Root node",
  "tree.childOf": "Child of {name}",
  "tree.nodeCount": "{count} nodes",
  "tree.panel": "TREE PANEL",
  "tree.multiplePanels": "Each tree keeps its own editing panel.",
  "tree.contextHint": "Click or right-click to edit this node",
  "tree.saveNode": "Save node",
  "tree.createNode": "Create node",
  "tree.editNode": "Edit node",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a node to make it the parent.",
  "tree.connection": "Connection",
  "tree.disconnection": "Disconnection",
  "tree.deleteNode": "Delete node",
  "tree.rename": "Rename",
  "tree.renameTree": "Rename tree",
  "tree.saveTreeName": "Save tree",
  "tree.rearrange": "Rearrange",
  "tree.delete": "Delete",
  "tree.confirmDelete": "Delete tree?",
  "tree.confirmDeleteCopy": "This permanently removes the tree, its dependent local models, and any platform link to it.",
  "tree.confirmDeleteAction": "Delete tree",
  "tree.canvasHint": "Right-click empty space to create a root node. Click or right-click a node to edit it. Drag a node to reposition its branch.",
  "tree.empty": "No nodes are in this local tree yet.",
  "tree.addTag": "Add a tag",
  "tree.addCopy": "Tags stay local. Adding a node creates a new tree revision.",
  "tree.tagName": "TAG NAME",
  "tree.add": "Add local tag",
  "tree.newTree": "New tag tree",
  "tree.newCopy": "A new tree is a reusable library asset. Bind it deliberately to a browser platform.",
  "tree.treeName": "TREE NAME",
  "tree.create": "Create tree",
  "model.title": "Local model",
  "model.copy": "Build local text-embedding and neural-classifier assets from the tree and approved classification data you choose.",
  "model.sharedLibrary": "SHARED LIBRARY",
  "model.multiplePanels": "Each local model keeps its own training panel.",
  "model.newModel": "New local model",
  "model.modelName": "MODEL NAME",
  "model.create": "Create model",
  "model.panel": "MODEL PANEL",
  "model.version": "Version {value}",
  "model.rename": "Rename model",
  "model.delete": "Delete model",
  "model.confirmDelete": "Delete this local model?",
  "model.confirmDeleteCopy": "This removes its stored neural artifact and cannot be undone.",
  "model.setup": "Model setup",
  "model.setupCopy": "Choose the exact local assets this model will train against. Changing setup clears its trained artifact.",
  "model.targetTree": "TARGET TREE",
  "model.classificationPlatform": "CLASSIFICATION-DATA PLATFORM",
  "model.baseLanguageModel": "BASE LANGUAGE MODEL",
  "model.baseCopy": "Optional package selection. This build trains the compact local embedding until a selected package is downloaded and activated.",
  "model.base.none": "None · compact local embedding",
  "model.base.allMiniLML6V2": "all-MiniLM-L6-v2",
  "model.base.allMPNetBaseV2": "all-mpnet-base-v2",
  "model.base.multilingualE5Small": "multilingual-e5-small",
  "model.base.multilingualE5Base": "multilingual-e5-base",
  "model.base.multilingualE5Large": "multilingual-e5-large",
  "model.base.bgeM3": "bge-m3",
  "model.trainingScope": "{records} approved records · {tags} available tags",
  "model.train": "Train local model",
  "model.trainedRun": "Trained from {records} records · {updates} label updates · {epochs} passes",
  "model.untrained": "Set up this model, then run an explicit local training pass.",
  "model.empty": "No local model assets yet. Create one to choose its tree, data platform, base model, and explicit training run.",
  "model.ready": "READY",
  "model.needsTraining": "NEEDS TRAINING",
  "model.models": "MODELS",
  "model.labels": "APPROVED LABELS",
  "model.versions": "VERSION",
  "model.active": "Active compatible model",
  "model.activeCopy": "A platform may activate one model whose tree and dataset revisions exactly match.",
  "model.none": "No local model",
  "model.boundRevisions": "Tree r{tree} · Data r{data}",
  "model.localTraining": "Explicit local training",
  "model.trainingCopy": "Training is user-controlled local work. Browsing-time inference remains fast and local.",
  "model.passes": "TRAINING PASSES",
  "model.explicitAction": "LOCAL ACTION",
  "model.backup": "Advanced backup",
  "model.backupCopy": "Optional local snapshots are owner-code gated and never leave this Mac.",
  "model.advanced": "Backup settings",
  "model.backupStatus": "Latest plus {count} previous snapshots",
  "llm.title": "LLM assist",
  "llm.copy": "Explicit provider work only. Suggestions remain records for your review; token use is retained locally.",
  "llm.usage": "Token usage ledger",
  "llm.usageCopy": "Each explicit provider attempt retains its reservation or settled token use locally.",
  "llm.tokenLine": "Input {input} · output {output} · other {other}",
  "llm.noUsage": "No provider request has reserved tokens yet.",
  "llm.status.reserved": "Reserved",
  "llm.status.possiblySent": "Possibly sent",
  "llm.status.settled": "Settled",
  "llm.status.cancelled": "Cancelled",
  "llm.status.uncertain": "Uncertain",
  "bridge.title": "Browser bridge",
  "bridge.copy": "Chrome and Edge request a versioned decision from this Mac. Incomplete bindings always fail open.",
  "bridge.macOnly": "MACOS LOCAL",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, compatible model, and optional named policy.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "ASSET BINDING",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.policy": "Named browser policies",
  "bridge.policyCopy": "Policies stay with the platform binding; the bridge can only request an existing local policy ID.",
  "bridge.configure": "Configure locally",
  "bridge.noPolicy": "No named policies are attached to the current bridge binding.",
  "data.title": "Classification data",
  "data.copy": "An immutable local ledger records manual and LLM-assisted classifications with their review state and provenance.",
  "data.records": "{count} RECORDS",
  "data.manual": "Manual classification",
  "data.manualCopy": "Approved manual labels are retained in the active platform dataset and can be used for training.",
  "data.entryTitle": "ENTRY TITLE",
  "data.tagIDs": "TAG IDS",
  "data.tagIDsHint": "Comma separated local tag IDs",
  "data.record": "Record manual classification",
  "data.ledger": "Classification ledger",
  "data.ledgerCopy": "Approved manual labels and reviewable LLM suggestions remain separate in provenance, not in datasets.",
  "data.empty": "No classification records are retained in this dataset yet.",
  "data.origin.manual": "Manual",
  "data.origin.llmAssist": "LLM assist",
  "data.origin.legacy": "Legacy import",
  "data.review.approved": "Approved",
  "data.review.pending": "Pending review",
  "data.review.rejected": "Rejected"
});
